project:
  type: website
  resources:
    - "recordings/*.html"
  output-dir: docs/463a01339cf0f456ba54a1849df50d1a22c247e3
  preview:
    port: 4321
  post-render:
    - _pw_protect.py

website:
  favicon: "favicon.png"
  title: "DSAN 5000"
  google-analytics: "G-ETYTX4E16L"
  #sidebar:
  #  title: "DSAN 5000<br><span class='subtitle'>Fall 2023, Georgetown, Prof. Jacobs <a href='mailto:jj1088@georgetown.edu' target='_blank'><i class='bi bi-envelope-at ps-1 pe-1'></i></a><span class='section-info'><span class='subtitle'>Section 02 (Tue 12:30pm-3pm)</span><br><span class='subsubtitle'>Intercultural Center 219</span></span><br><span class='subsubtitle'>Sec 02 <a href='#' onclick='window.quartoToggleSection(); return false;'><i class='bi dsan-section-toggle ps-1 pe-1'></i></a> Sec 03</span><br><span class='subtitle'><i class='bi bi-sun'></i>/<i class='bi bi-moon'></i></span>"
  
  #"<span style="width: 100% !important; height: 1px !important; display: inline-flex !important; border: 1px solid #cccccd !important;" class='py-0 my-0'></span>"
  sidebar:
    title: >
      DSAN 5000
      <br>

      <span class='subtitle'>Fall 2023, Georgetown, Prof. Jacobs <a href='mailto:jj1088@georgetown.edu' target='_blank'><i class='bi bi-envelope-at ps-1'></i></a>

      <span class="btn-group section-toggle" role="group" aria-label="Basic radio toggle button group" style="display: inline-flex !important; margin-top: 4px !important; width: 100% !important;">

      <input type="radio" class="btn-check pt-5" name="btnradio" id="btn-radio-02" autocomplete="off" onclick="window.toggleSectionClicked('02');">
      <label class="btn btn-outline-secondary btn-sm" for="btn-radio-02" id='btn-label-02'>Sec 02</label>

      <input type="radio" class="btn-check" name="btnradio" id="btn-radio-03" autocomplete="off" onclick="window.toggleSectionClicked('03');">
      <label class="btn btn-outline-secondary btn-sm" for="btn-radio-03" id="btn-label-03">Sec 03</label>
      </span>
      <br>

      <span class='section-info subsubtitle'>
        <span class='sec-day'>Tue</span> <span class='sec-time'>12:30pm-3pm</span>
        <br>
        <span class='sec-room'>ICC 219</span>
        <br>
        <a class="sec-zoom-link" href='https://georgetown.zoom.us/j/93896372980' target='_blank' class='icon-link' style='text-decoration: none !important;'>
        <span class='icon pe-1'>
          <svg class="bi" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 50 50">
            <path d="M33.619,4H16.381C9.554,4,4,9.554,4,16.381v17.238C4,40.446,9.554,46,16.381,46h17.238C40.446,46,46,40.446,46,33.619	V16.381C46,9.554,40.446,4,33.619,4z M30,30.386C30,31.278,29.278,32,28.386,32H15.005C12.793,32,11,30.207,11,27.995v-9.382	C11,17.722,11.722,17,12.614,17h13.382C28.207,17,30,18.793,30,21.005V30.386z M39,30.196c0,0.785-0.864,1.264-1.53,0.848l-5-3.125	C32.178,27.736,32,27.416,32,27.071v-5.141c0-0.345,0.178-0.665,0.47-0.848l5-3.125C38.136,17.54,39,18.019,39,18.804V30.196z"></path>
          </svg></span>S<span class='sec-num'>02</span> Zoom Link <i class='bi bi-box-arrow-up-right ps-1'></i>
        </a>
      </span>
    tools:
      - icon: github
        href: https://github.com
        text: "Git"
    contents:
      - href: "https://jfh.georgetown.domains/dsan5000/"
        text: "<i class=\"bi bi-arrow-left\" style=\"margin-right: 4px\"></i>Main Course Page"
      - "---"
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i> Section <span class='sec-num'>02</span> Home"
      - href: w01/index.qmd
        text: "Week 1: <span class='sec-w01-date'>Aug 23</span>"
      - href: w02/index.qmd
        text: "Week 2: <span class='sec-w02-date'>Aug 29</span>"
      - href: w03/index.qmd
        text: "Week 3: <span class='sec-w03-date'>Sep 6</span>"
      - href: w04/index.qmd
        text: "Week 4: <span class='sec-w04-date'>Sep 12</span>"
      - href: w05/index.qmd
        text: "Week 5: <span class='sec-w05-date'>Sep 19</span>"
      - href: w06/index.qmd
        text: "Week 6: <span class='sec-w06-date'>Sep 26</span>"
      - href: recordings/index.qmd
        text: "Lecture Recordings"
      - "---"
      - href: extra-videos/index.qmd
        text: "Extra Videos"
      - href: writeups/index.qmd
        text: "Extra Writeups"
      - "---"
      - href: "https://georgetown.instructure.com/courses/173310"
        text: "Course Canvas Page <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"
      - href: "https://calendar.app.google/yMnESMtMNPdKEaPz5"
        text: "Book Office Hours <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"
      - href: "https://forms.gle/TH1yLitU9dTfB4sg8"
        text: "Suggestion Box <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"

format:
  html:
    theme: cosmo
    #  light: cosmo
    #  dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://code.jquery.com/jquery-3.7.1.slim.min.js'></script><script src='/jjcustom.js'></script>"
      #text: "<script src='https://get.mavo.io/stable/mavo.es5.min.js'></script><link rel='stylesheet' href='https://get.mavo.io/stable/mavo.min.css'>"
