project:
  type: website
  resources:
    - "recordings/*.html"
  output-dir: docs/463a01339cf0f456ba54a1849df50d1a22c247e3
  preview:
    port: 4321
  post-render:
    - _pw_protect.py

website:
  favicon: "favicon.png"
  title: "DSAN 5000"
  google-analytics: "G-ETYTX4E16L"
  sidebar:
    title: "DSAN 5000"
    contents:
      - href: "https://jfh.georgetown.domains/dsan5000/"
        text: "<i class=\"bi bi-arrow-left\" style=\"margin-right: 4px\"></i>Main Course Page"
      - "---"
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i> Section <span class='sec-num'>02</span> Home"
      - href: w01/index.qmd
        text: "Week 1: <span class='sec-w01-date'>Aug 23</span>"
      - href: w02/index.qmd
        text: "Week 2: <span class='sec-w02-date'>Aug 29</span>"
      - href: w03/index.qmd
        text: "Week 3: <span class='sec-w03-date'>Sep 6</span>"
      - href: w04/index.qmd
        text: "Week 4: <span class='sec-w04-date'>Sep 12</span>"
      - href: w05/index.qmd
        text: "Week 5: <span class='sec-w05-date'>Sep 19</span>"
      - href: w06/index.qmd
        text: "Week 6: <span class='sec-w06-date'>Sep 26</span>"
      - href: recordings/index.qmd
        text: "Lecture Recordings"
      - "---"
      - href: extra-videos/index.qmd
        text: "Extra Videos"
      - href: writeups/index.qmd
        text: "Extra Writeups"
      - "---"
      - href: "https://georgetown.instructure.com/courses/173310"
        text: "Course Canvas Page <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"
      - href: "https://calendar.app.google/yMnESMtMNPdKEaPz5"
        text: "Book Office Hours <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"
      - href: "https://forms.gle/TH1yLitU9dTfB4sg8"
        text: "Suggestion Box <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"

format:
  html:
    theme: cosmo
    #  light: cosmo
    #  dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://code.jquery.com/jquery-3.7.1.slim.min.js'></script><script src='/jjcustom.js'></script>"
      #text: "<script src='https://get.mavo.io/stable/mavo.es5.min.js'></script><link rel='stylesheet' href='https://get.mavo.io/stable/mavo.min.css'>"
