---
title: "Feature Selection in Python"
date: last-modified
metadata-files:
  - "../../_doc-meta.yml"
---

Since my last two data adventures were focused on <a href='https://jjacobs.me/dsan5000/463a01339cf0f456ba54a1849df50d1a22c247e3/writeups/data-cleaning/clean_data.html' target='_blank'>public health data</a> and <a href='https://jjacobs.me/dsan5000/463a01339cf0f456ba54a1849df50d1a22c247e3/writeups/eda-seaborn/THOR_EDA_with_Seaborn.html' target='_blank'>international relations data</a>, this week I'm going to focus on the topic that is tied for the most common topic students are doing for their projects, namely, **sports data**!

This time, rather than worrying about cleaning the data or exploring the data, we will "fast forward" to a particular task: **using** the data to accomplish a task, namely, **predicting success in the NBA (National Basketball Association)**.

I chose the NBA because, unlike the NFL (National Football League) and the MLB (Major League Baseball) for example, the NBA is popular both inside **and** outside the US. But, if you don't know anything about the NBA don't worry, I will do my best to explain what's going on at each point in the lab.

## The Dataset

For this lab we'll be analyzing a **panel dataset** where each row represents a **(team, season) pair**.

A complicating factor in analyzing NBA data is that, unlike other sports like baseball, each NBA season spans **two years**: meaning, for example, <a href='https://en.wikipedia.org/wiki/2022%E2%80%9323_NBA_season' target='_blank'>the most recent season</a> began in 2022 but ended in 2023. To make things easier for us, then, rather than recording seasons as two-year spans, I have simplified the dataset so that the **year** for each row represents the year in which the **playoffs** for that season occurred. To make this as clear as possible when examining the dataset, I've named the year variable `po_year` (for **playoff year**).

Let's take a look at the first few rows of the dataset:

```{python}

```