<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jeff Jacobs">
<meta name="dcterms.date" content="2023-10-15">

<title>DSAN 5000 - Midterm Prep Practice Problems</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ETYTX4E16L"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ETYTX4E16L', { 'anonymize_ip': true});
</script>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script><script src="../../jjcustom.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      DSAN 5000
      </li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">DSAN 5000</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://jfh.georgetown.domains/dsan5000/" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><i class="bi bi-arrow-left" style="margin-right: 4px"></i>Main Course Page</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><i class="bi bi-house pe-1"></i> Section <span class="sec-num">02</span> Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1: <span class="sec-w01-date">Aug 23</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2: <span class="sec-w02-date">Aug 29</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3: <span class="sec-w03-date">Sep 6</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4: <span class="sec-w04-date">Sep 12</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w05/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5: <span class="sec-w05-date">Sep 19</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w06/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6: <span class="sec-w06-date">Sep 26</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../w07/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7: <span class="sec-w07-date">Oct 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../recordings/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture Recordings</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../extra-videos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra Videos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../writeups/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra Writeups</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../cheatsheet-code/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Coding Cheatsheet</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://georgetown.instructure.com/courses/173310" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Canvas Page <i class="bi bi-box-arrow-up-right ps-1"></i></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://calendar.app.google/yMnESMtMNPdKEaPz5" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Book Office Hours <i class="bi bi-box-arrow-up-right ps-1"></i></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://forms.gle/TH1yLitU9dTfB4sg8" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Suggestion Box <i class="bi bi-box-arrow-up-right ps-1"></i></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-science-fundamentals" id="toc-data-science-fundamentals" class="nav-link active" data-scroll-target="#data-science-fundamentals">Data Science Fundamentals</a>
  <ul class="collapse">
  <li><a href="#filepaths" id="toc-filepaths" class="nav-link" data-scroll-target="#filepaths">Filepaths</a></li>
  <li><a href="#http" id="toc-http" class="nav-link" data-scroll-target="#http">HTTP</a></li>
  <li><a href="#gitgithub" id="toc-gitgithub" class="nav-link" data-scroll-target="#gitgithub">Git/GitHub</a></li>
  <li><a href="#python-object-oriented-programming-overview" id="toc-python-object-oriented-programming-overview" class="nav-link" data-scroll-target="#python-object-oriented-programming-overview">Python: Object-Oriented Programming (Overview)</a></li>
  <li><a href="#python-object-oriented-programming-practice-problem" id="toc-python-object-oriented-programming-practice-problem" class="nav-link" data-scroll-target="#python-object-oriented-programming-practice-problem">Python: Object-Oriented Programming (Practice Problem)</a></li>
  <li><a href="#conda" id="toc-conda" class="nav-link" data-scroll-target="#conda">Conda</a></li>
  <li><a href="#typecasting-overview" id="toc-typecasting-overview" class="nav-link" data-scroll-target="#typecasting-overview">Typecasting: Overview</a></li>
  <li><a href="#typecasting-practice-problem" id="toc-typecasting-practice-problem" class="nav-link" data-scroll-target="#typecasting-practice-problem">Typecasting: Practice Problem</a></li>
  </ul></li>
  <li><a href="#steps-in-the-data-science-pipeline" id="toc-steps-in-the-data-science-pipeline" class="nav-link" data-scroll-target="#steps-in-the-data-science-pipeline">Steps in the Data Science Pipeline</a>
  <ul class="collapse">
  <li><a href="#data-cleaning-overview" id="toc-data-cleaning-overview" class="nav-link" data-scroll-target="#data-cleaning-overview">Data Cleaning: Overview</a></li>
  <li><a href="#data-cleaning-practice-problems" id="toc-data-cleaning-practice-problems" class="nav-link" data-scroll-target="#data-cleaning-practice-problems">Data Cleaning: Practice Problems</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">EDA</a></li>
  </ul></li>
  <li><a href="#text-analysis" id="toc-text-analysis" class="nav-link" data-scroll-target="#text-analysis">Text Analysis</a></li>
  <li><a href="#machine-learning" id="toc-machine-learning" class="nav-link" data-scroll-target="#machine-learning">Machine Learning</a>
  <ul class="collapse">
  <li><a href="#types-of-learning-methods" id="toc-types-of-learning-methods" class="nav-link" data-scroll-target="#types-of-learning-methods">Types of Learning Methods</a></li>
  <li><a href="#distance-metrics" id="toc-distance-metrics" class="nav-link" data-scroll-target="#distance-metrics">Distance Metrics</a></li>
  <li><a href="#precision-recall-f1-score" id="toc-precision-recall-f1-score" class="nav-link" data-scroll-target="#precision-recall-f1-score">Precision, Recall, F1 Score</a></li>
  <li><a href="#loss-functions" id="toc-loss-functions" class="nav-link" data-scroll-target="#loss-functions">Loss Functions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Midterm Prep Practice Problems</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Extra Writeups</div>
  </div>
  </div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Jeff Jacobs </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="mailto:jj1088@georgetown.edu" target="_blank">jj1088@georgetown.edu</a>
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 15, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="hidden">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>cb_palette <span class="op">=</span> [<span class="st">"#E69F00"</span>, <span class="st">"#56B4E9"</span>, <span class="st">"#009E73"</span>, <span class="st">"#F0E442"</span>, <span class="st">"#0072B2"</span>, <span class="st">"#D55E00"</span>, <span class="st">"#CC79A7"</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> disp(df, floatfmt<span class="op">=</span><span class="st">'g'</span>, include_index<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> Markdown(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    df.to_markdown(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>      floatfmt<span class="op">=</span>floatfmt,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      index<span class="op">=</span>include_index</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> summary_to_df(summary_obj, corner_col <span class="op">=</span> <span class="st">''</span>):</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    reg_df <span class="op">=</span> pd.DataFrame(summary_obj.tables[<span class="dv">1</span>].data)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    reg_df.columns <span class="op">=</span> reg_df.iloc[<span class="dv">0</span>]</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    reg_df <span class="op">=</span> reg_df.iloc[<span class="dv">1</span>:].copy()</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Save index col</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    index_col <span class="op">=</span> reg_df[<span class="st">''</span>]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Drop for now, so it's all numeric</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    reg_df.drop(columns<span class="op">=</span>[<span class="st">''</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    reg_df <span class="op">=</span> reg_df.<span class="bu">apply</span>(pd.to_numeric)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    my_round <span class="op">=</span> <span class="kw">lambda</span> x: <span class="bu">round</span>(x, <span class="dv">2</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    reg_df <span class="op">=</span> reg_df.<span class="bu">apply</span>(my_round)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    numeric_cols <span class="op">=</span> reg_df.columns</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add index col back in</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    reg_df.insert(loc<span class="op">=</span><span class="dv">0</span>, column<span class="op">=</span>corner_col, value<span class="op">=</span>index_col)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sigh. Have to escape | characters?</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    reg_df.columns <span class="op">=</span> [c.replace(<span class="st">"|"</span>,<span class="st">"\|"</span>) <span class="cf">for</span> c <span class="kw">in</span> reg_df.columns]</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> reg_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Update Log">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Update Log
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><em>2023-10-15, 8:30pm EST</em>: Added example multiple choice problems on <strong>Distance Metrics</strong></li>
<li><em>2023-10-15, 8pm EST</em>: Added example essay question on <strong>Classification vs.&nbsp;Regression</strong>, and how to transform from one to the other</li>
<li><em>2023-10-15, 7pm EST</em>: Added example multiple choice and essay questions on <strong>EDA</strong></li>
<li><em>2023-10-15, 6pm EST</em>: Added R and Python code demonstrating <strong>Wide vs.&nbsp;Long Datasets</strong> and how to transform data between these two formats</li>
<li><em>2023-10-15, 5pm EST</em>: Added overviews and practice problems on <strong>Conda</strong>, <strong>Typecasting</strong></li>
<li><em>2023-10-14, 11pm EST</em>: Added overview of <strong>object-oriented programming in Python</strong>, along with a practice problem on this topic.</li>
<li><em>2023-10-14, 10pm EST</em>: Initial version of document, emailed out in announcement to students.</li>
</ul>
</div>
</div>
<p>This writeup is organized so that each section represents a particular topic/subtopic that the exam may cover, such that the example problems within each topic/subtopic will prepare you for questions on that topic/subtopic which may appear on the midterm!</p>
<section id="data-science-fundamentals" class="level2">
<h2 class="anchored" data-anchor-id="data-science-fundamentals">Data Science Fundamentals</h2>
<section id="filepaths" class="level3">
<h3 class="anchored" data-anchor-id="filepaths">Filepaths</h3>
<p>For these practice problems, assume we have a directory structure on our computer that looks as follows, and that <strong>this is the entire directory structure</strong> (that is, there are no additional files or folders on the computer that are not displayed in the diagram).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<svg width="672" height="480" viewbox="0.00 0.00 260.50 398.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 394)">
<title>
G
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-394 256.5,-394 256.5,4 -4,4"></polygon> <!-- nodeRoot --> <g id="node1" class="node">
<title>
nodeRoot
</title>
<text text-anchor="start" x="126.8" y="-369.4" font-family="Courier New" font-weight="bold" font-size="14.00">/</text> <polygon fill="none" stroke="black" points="73.5,-339 73.5,-361 188.5,-361 188.5,-339 73.5,-339"></polygon> <text text-anchor="start" x="93.19" y="-345.4" font-family="Courier New" font-size="14.00">file1.txt</text> <polygon fill="none" stroke="black" points="73.5,-315 73.5,-337 188.5,-337 188.5,-315 73.5,-315"></polygon> <text text-anchor="start" x="93.19" y="-321.4" font-family="Courier New" font-size="14.00">file2.txt</text> <polygon fill="none" stroke="black" points="73.5,-291 73.5,-313 188.5,-313 188.5,-291 73.5,-291"></polygon> <text text-anchor="start" x="76.39" y="-297.4" font-family="Courier New" font-size="14.00">rootImage.jpg</text> <polygon fill="none" stroke="black" points="70,-288 70,-386 191,-386 191,-288 70,-288"></polygon> </g> <!-- nodeUsers --> <g id="node2" class="node">
<title>
nodeUsers
</title>
<text text-anchor="start" x="51.5" y="-191.4" font-family="Courier New" font-weight="bold" font-size="14.00">Users</text> <polygon fill="none" stroke="black" points="46.5,-182 46.5,-208 98.5,-208 98.5,-182 46.5,-182"></polygon> </g> <!-- nodeRoot&#45;&gt;nodeUsers --> <g id="edge1" class="edge">
<title>
nodeRoot-&gt;nodeUsers
</title>
<path fill="none" stroke="black" d="M108.9,-283.87C100.29,-263.07 90.74,-240.02 83.58,-222.75"></path> <polygon fill="black" stroke="black" points="86.73,-221.21 79.67,-213.31 80.26,-223.89 86.73,-221.21"></polygon> </g> <!-- nodeApps --> <g id="node3" class="node">
<title>
nodeApps
</title>
<text text-anchor="start" x="138.09" y="-227.4" font-family="Courier New" font-weight="bold" font-size="14.00">Applications</text> <polygon fill="none" stroke="black" points="135.5,-197 135.5,-219 241.5,-219 241.5,-197 135.5,-197"></polygon> <text text-anchor="start" x="154.89" y="-203.4" font-family="Courier New" font-size="14.00">App1.app</text> <polygon fill="none" stroke="black" points="135.5,-173 135.5,-195 241.5,-195 241.5,-173 135.5,-173"></polygon> <text text-anchor="start" x="154.89" y="-179.4" font-family="Courier New" font-size="14.00">App2.app</text> <polygon fill="none" stroke="black" points="135.5,-149 135.5,-171 241.5,-171 241.5,-149 135.5,-149"></polygon> <text text-anchor="start" x="138.09" y="-155.4" font-family="Courier New" font-size="14.00">appImage.png</text> <polygon fill="none" stroke="black" points="132.5,-146 132.5,-244 244.5,-244 244.5,-146 132.5,-146"></polygon> </g> <!-- nodeRoot&#45;&gt;nodeApps --> <g id="edge2" class="edge">
<title>
nodeRoot-&gt;nodeApps
</title>
<path fill="none" stroke="black" d="M152.1,-283.87C155.64,-275.31 159.35,-266.36 162.98,-257.59"></path> <polygon fill="black" stroke="black" points="166.29,-258.75 166.88,-248.17 159.82,-256.07 166.29,-258.75"></polygon> </g> <!-- nodeJeff --> <g id="node4" class="node">
<title>
nodeJeff
</title>
<text text-anchor="start" x="60.4" y="-85.4" font-family="Courier New" font-weight="bold" font-size="14.00">jpj</text> <polygon fill="none" stroke="black" points="11.5,-55 11.5,-77 134.5,-77 134.5,-55 11.5,-55"></polygon> <text text-anchor="start" x="39.39" y="-61.4" font-family="Courier New" font-size="14.00">doc1.qmd</text> <polygon fill="none" stroke="black" points="11.5,-31 11.5,-53 134.5,-53 134.5,-31 11.5,-31"></polygon> <text text-anchor="start" x="39.39" y="-37.4" font-family="Courier New" font-size="14.00">doc2.qmd</text> <polygon fill="none" stroke="black" points="11.5,-7 11.5,-29 134.5,-29 134.5,-7 11.5,-7"></polygon> <text text-anchor="start" x="14.19" y="-13.4" font-family="Courier New" font-size="14.00">jeffImage.jpeg</text> <polygon fill="none" stroke="black" points="8,-4 8,-102 137,-102 137,-4 8,-4"></polygon> </g> <!-- nodeUsers&#45;&gt;nodeJeff --> <g id="edge3" class="edge">
<title>
nodeUsers-&gt;nodeJeff
</title>
<path fill="none" stroke="black" d="M72.5,-176.83C72.5,-161.57 72.5,-138.31 72.5,-116.11"></path> <polygon fill="black" stroke="black" points="76,-116.02 72.5,-106.02 69,-116.02 76,-116.02"></polygon> </g> </g>
</svg>
</div>
</div>
</div>
</div>
<p>The way this diagram works is:</p>
<ul>
<li>The <strong>names of folders</strong> are bolded, and if a <strong>folder</strong> <code>X</code> is contained within a folder <code>Y</code>, then the diagram has an arrow between folder <code>X</code> and folder <code>Y</code>.
<ul>
<li>So, for example, since the <strong>Users</strong> folder here is a subfolder of the <strong>/</strong> folder (the <em>root folder</em>), there is an arrow pointing from the box with label <strong>/</strong> to the box with label <strong>Users</strong>.</li>
</ul></li>
<li>If a <strong>file</strong> <code>f</code> is contained within a folder, then the file is displayed as a box within the box representing the folder.
<ul>
<li>So, for example, since the document <code>doc1.qmd</code> is contained within the folder labeled <strong><code>jpj</code></strong>, there is a smaller box labeled <code>doc1.qmd</code> within the box labeled <strong><code>jpj</code></strong>.</li>
</ul></li>
</ul>
<p>Please answer the following questions, with reference to this directory structure:</p>
<ol type="1">
<li><p><strong>True</strong> or <strong>False</strong>: If I am writing the document <code>doc1.qmd</code>, and I want to include the image <code>jeffImage.jpeg</code> from within the same folder, I can use the <strong>relative path</strong> <code>jeffImage.jpeg</code>, like</p>
<pre><code>![Photo caption](jeffImage.jpeg)</code></pre></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>True</strong>: Since <code>jeffImage.jpeg</code> is in the same directory as the <code>.qmd</code> file we’re authoring, we can reference it using a relative path to the file which is actually just the name of the file (since the Quarto compiler doesn’t need to navigate to any other folder to retrieve the file).</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><p><strong>True</strong> or <strong>False</strong>: If I am writing the document <code>doc1.qmd</code>, and I want to include the image <code>jeffImage.jpeg</code> from within the same folder, I can use the <strong>absolute path</strong> <code>/Users/jpj/jeffImage.jpeg</code>, like</p>
<pre><code>![Photo caption](/Users/jpj/jeffImage.jpeg)</code></pre></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>True</strong>: In this case, it actually doesn’t matter where the <code>.qmd</code> file we’re authoring exists on the filesystem, since we’re using an <strong>absolute path</strong>. This means that, no matter where the <code>.qmd</code> file is, the Quarto compiler will be able to find the image file, by starting at the root directory <code>/</code>, navigating to the <code>Users</code> subdirectory, then the <code>jpj</code> subdirectory, and finally locating the <code>jeffImage.jpeg</code> file within this <code>jpj</code> subdirectory.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><p><strong>True</strong> or <strong>False</strong>: If I am writing the document <code>doc1.qmd</code>, and I want to include the image <code>jeffImage.jpeg</code> from within the same folder, I can use the <strong>relative path</strong> <code>images/jeffImage.jpeg</code>, like</p>
<pre><code>![Photo caption](images/jeffImage.jpeg)</code></pre></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>False</strong>: In this case, the Quarto compiler will crash with an error. It will attempt to look for an <code>images</code> subdirectory within the directory where the <code>.qmd</code> file is located, and it will not find a subdirectory called <code>images</code> (since there are no subdirectories within the <code>jpj</code> folder), producing an error.</p>
</div>
</div>
</div>
</section>
<section id="http" class="level3">
<h3 class="anchored" data-anchor-id="http">HTTP</h3>
<p>Please match each of the following <strong>HTTP codes</strong> on the left to their <strong>meanings</strong> on the right (that is, what it means if we receive that code as a response to our call to the server):</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">HTTP Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">301</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">403</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">500</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 66.7%;justify-content: center;">
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Error: the server software could not find the requested file or data</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">Successful request (the body of the request should thus contain the html code, or json data, or whatever else was requested)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">Server error: the server software crashed or experienced an error while trying to respond to the request</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">Not authorized: the requested file is protected by a password that was not given correctly, for example, or it is restricted only to logged-in users and the user making the request was not logged in.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">Redirect: A response with this code indicates that the server is going to redirect the user to a different page within the website, or a different website entirely.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>B</strong>. 200 is the HTTP code for a <strong>successful request</strong></li>
<li><strong>E</strong>. 301 is the HTTP code for a <strong>redirect</strong></li>
<li><strong>D</strong>. 403 is the HTTP code for a <strong>non-authorized</strong> request</li>
<li><strong>A</strong>. 404 is the HTTP code for <strong>file not found</strong></li>
<li><strong>C</strong>. 500 is the HTTP code for an <strong>unknown/unspecified server error</strong></li>
</ol>
</div>
</div>
</div>
</section>
<section id="gitgithub" class="level3">
<h3 class="anchored" data-anchor-id="gitgithub">Git/GitHub</h3>
<p>[From <a href="../../w04/index.html" target="_blank">Week 04 Slides</a>] Please match each of the following <code>git</code> commands with the description of what it does:</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><code>git clone</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>git init</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><code>git add</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;"><code>git reset</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;"><code>git status</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;"><code>git commit -m "message"</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;"><code>git push</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;"><code>git pull</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;"><code>git merge</code></td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 66.7%;justify-content: center;">
<table class="table">
<colgroup>
<col style="width: 1%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Downloads a repo from the web to our local computer</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">Merges remote versions of files with local versions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">Creates a new, blank Git repository on our local computer (configuration/change-tracking stored in <code>.git</code> subfolder)</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">Shows currently staged files and their status (created, modified, deleted)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">“Saves” the current version of all staged files, ready to be pushed to a backup dir or remote server like GitHub</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: left;">Transmits local commits to remote server</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: left;"><strong>Stages</strong> a file(s): Git will now track changes in this file(s)</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: left;">Downloads commits from remote server to local computer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: left;">Undoes a <code>git add</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>A</strong>: The <code>git clone</code> command downloads a repo from the web to our local computer</li>
<li><strong>C</strong>: The <code>git add</code> command creates a new, blank Git repository on our local computer (configuration/change-tracking stored in <code>.git</code> subfolder)</li>
<li><strong>G</strong>: The <code>git add</code> command <strong>stages</strong> files; Git will now track changes in these files</li>
<li><strong>I</strong>: The <code>git reset</code> command undoes a previous <code>git add</code> command</li>
<li><strong>D</strong>: The <code>git status</code> command shows currently staged files and their status (created, modified, deleted)</li>
<li><strong>E</strong>: The <code>git commit</code> command “saves” the current version of all staged files, ready to be pushed to a backup dir or remote server like GitHub</li>
<li><strong>F</strong>: The <code>git push</code> command transmits local commits to remote server</li>
<li><strong>H</strong>: The <code>git pull</code> command downloads commits from remote server to local computer</li>
<li><strong>B</strong>: The <code>git merge</code> command merges remote versions of files with local versions</li>
</ol>
</div>
</div>
</div>
</section>
<section id="python-object-oriented-programming-overview" class="level3">
<h3 class="anchored" data-anchor-id="python-object-oriented-programming-overview">Python: Object-Oriented Programming (Overview)</h3>
<p>We didn’t get to talk about this much in class, so here I will give a quick overview and then a practice problem afterwards.</p>
<p>The way that <a href="https://en.wikipedia.org/wiki/Object-oriented_programming" target="_blank">Object-Oriented Programming</a> is implemented in Python is as follows:</p>
<p>Python provides you with a set of “default” object types: starting from the base <a href="https://docs.python.org/3/library/functions.html#object" target="_blank"><code>object</code> class</a>, for example, it provides classes like <code>int</code>, <code>float</code>, <code>string</code>, <code>boolean</code>, and so on.</p>
<p>However, sometimes these base classes on their own, or combinations of them, cannot serve the purposes that you need for your particular project/application. In these cases, you can create your own <strong>custom classes</strong>, with syntax that looks like the following</p>
<p><em>(<strong>NOTE</strong>: Despite the fact that we’re not explicitly defining <code>Vehicle</code> here to be a sub-class of any other class, <strong>by default</strong> in Python <strong>all classes are subclasses of the <code>object</code> class mentioned above</strong>)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Vehicle:</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, maker, num_wheels):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.maker <span class="op">=</span> maker</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.num_wheels <span class="op">=</span> num_wheels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By defining the class using the line <code>class Vehicle</code> at the top, and then defining a <strong>constructor function</strong> called <code>__init__()</code>, we can now create new objects with the <strong>type</strong> <code>Vehicle</code> by using syntax like the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>my_vehicle <span class="op">=</span> Vehicle(<span class="st">"Toyota"</span>, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Which will call the <code>__init__()</code> function defined above, such that now the value <code>"Toyota"</code> will be stored in the <strong>instance variable</strong> called <code>maker</code> within the <code>my_car</code> object, and the value <code>4</code> will be stored in the instance variable called <code>num_wheels</code> within the <code>my_obj</code> object. The <strong>object</strong> <code>my_obj</code> here is therefore an <strong>instance</strong> of the class <code>Vehicle</code>.</p>
<p>This means that, from this point onwards, we can access this information (the values contained in <code>maker</code> and <code>num_wheels</code>) using the <strong>dot operator</strong> <code>.</code> on the object, like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_vehicle.maker, my_vehicle.num_wheels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Toyota 4</code></pre>
</div>
</div>
<p>Now that we’ve seen how to define a <strong>class</strong>, providing a <strong>template</strong> for creating objects, and how to <strong>create objects</strong> using the <strong>constructor function</strong> within a <strong>class</strong>, let’s now look at the notion of <strong>inheritance</strong>.</p>
<p><strong>An issue with OOP in <em>Python</em> (unlike many other languages) is that Python does <em>not</em> allow you to create multiple versions of the same function within the same class</strong>.</p>
<p>This means, for example, that we could <strong>not</strong> add a <code>start_vehicle()</code> function to our <code>Vehicle</code> class which would behave differently given different input types. The following new version of <code>Vehicle</code> will produce an error:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Vehicle:</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, maker, num_wheels):</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.maker <span class="op">=</span> maker</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.num_wheels <span class="op">=</span> num_wheels</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> start_vehicle(<span class="va">self</span>):</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">        Version for cars</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">        """</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Start the car</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> start_vehicle(<span class="va">self</span>):</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">        Version for motorcycles</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co">        """</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Start the motorcycle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So, if we find ourselves in a case where we want to model a <strong>hierarchy</strong> of more-general to more-specific versions of a class, we can use <strong>inheritance</strong> to define <strong>sub-classes</strong> of a given class which represent a more specific “version” of this class.</p>
<p>So, using our <code>Vehicle</code> class as our working example, we may find ourselves defining <strong>four-wheeled</strong> vehicles very often, since <strong>cars</strong> are common vehicles which always have four wheels, but also <strong>two-wheeled</strong> vehicles very often, since <strong>motorcycles</strong> are common vehicles which always have two wheels.</p>
<p>So, to make our lives easier, rather than having to specify the number of wheels each time we want to create an object representing a car or motorcycle, instead we can create <strong>sub-classes</strong> of <code>Vehicle</code> representing cars and motorcycles, as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Car(Vehicle):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, maker):</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>(maker, <span class="dv">4</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Motorcycle(Vehicle):</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, maker):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>(maker, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have these two sub-classes, defined in this way, we can create <strong><code>Car</code></strong> and <strong><code>Motorcycle</code></strong> objects, which will have those types (<code>Car</code> and <code>Motorcycle</code>, respectively) but will <strong>also</strong> both have type <code>Vehicle</code>, and will have their <code>num_wheels</code> value set automatically, without us having to provide these values explicitly to the <code>Car</code> and/or <code>Motorcycle</code> constructors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>my_car <span class="op">=</span> Car(<span class="st">"Toyota"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>my_motorcycle <span class="op">=</span> Motorcycle(<span class="st">"Kawasaki"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now, despite the fact that <code>my_car</code> and <code>my_motorcycle</code> are of different sub-types, since they are both objects of type <code>Vehicle</code> we know that we can access a field called <code>num_wheels</code> on both:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_car.num_wheels, my_motorcycle.num_wheels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4 2</code></pre>
</div>
</div>
<p>So, we can see from this output that <code>num_wheels</code> has been set correctly, automatically, despite the fact that we did not explicitly specify the values <code>4</code> or <code>2</code> when creating our <code>my_car</code> and <code>my_motorcycle</code> objects above.</p>
</section>
<section id="python-object-oriented-programming-practice-problem" class="level3">
<h3 class="anchored" data-anchor-id="python-object-oriented-programming-practice-problem">Python: Object-Oriented Programming (Practice Problem)</h3>
<p>Given the above overview, hopefully the following practice problem becomes more manageable!</p>
<p><strong>Fill in the blanks to make the statement correct, by choosing the correct answer from each dropdown menu</strong>:</p>
Defining a <select name="cars" id="cars" style="display: inline-block">
  <option value="answer1">class</option>
  <option value="answer2">string</option><option value="answer3">struct</option>
</select> in Python (which should include a constructor function with the name <select name="cars2" id="cars2" style="display: inline-block"><option value="answer1">__init__()</option><option value="answer2">__start__()</option><option value="answer3">__letsgooo__()</option></select>), allows us to create <b>objects</b>, each of which is <select><option value="answer1">an instance</option><option value="answer1">a version</option></select> of the class.
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Defining a <strong>class</strong> in Python (which should include a constructor function with the name <strong><code>__init__()</code></strong>), allows us to create <b>objects</b>, each of which is <strong>an instance</strong> of the class.</p>
</div>
</div>
</div>
</section>
<section id="conda" class="level3">
<h3 class="anchored" data-anchor-id="conda">Conda</h3>
<p><em>(Material from <a href="https://jfh.georgetown.domains/dsan5000/slides-and-labs/_site/content/slides/coding-methods/notes.html#conda" target="_blank"><strong>Week-02 course notes</strong></a>)</em></p>
<p>Please match each of the <code>conda</code> <strong>commands</strong> on the left with their corresponding <strong>descriptions</strong> on the right:</p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><code>conda deactivate</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>conda activate myenv</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><code>conda info --envs</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;"><code>conda remove --name myenv --all</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;"><code>conda rename -n old_name new_name</code></td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Remove an environment named “myenv”</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">Deactivate current environment</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">Rename an environment</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">List all environments</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">Activate an environment named <code>myenv</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>B</strong>: The <code>conda deactivate</code> command deactivates the current environment.</li>
<li><strong>E</strong>: The <code>conda activate myenv</code> command activates an environment named <code>myenv</code></li>
<li><strong>D</strong>: The <code>conda info --envs</code> command lists all environments</li>
<li><strong>A</strong>: The command <code>conda remove --name myenv --all</code> removes an environment named <code>myenv</code></li>
<li><strong>C</strong>: The command <code>conda rename -n old_name new_name</code> renames the environment named <code>old_name</code> to be named <code>new_name</code></li>
</ol>
</div>
</div>
</div>
</section>
<section id="typecasting-overview" class="level3">
<h3 class="anchored" data-anchor-id="typecasting-overview">Typecasting: Overview</h3>
<p>The concept of <strong>typecasting</strong> is one we didn’t get to discuss much in class, but it’s an operation that we use all the time when writing Python code: for example, every time we <strong>print the value of an <code>int</code> or <code>float</code> variable</strong>, we are implicitly <strong>typecasting</strong> the <code>int</code> or <code>float</code> to a <strong><code>string</code></strong> variable, as in the following example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>one_plus_one <span class="op">=</span> <span class="dv">1</span> <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"One plus one is </span><span class="sc">{</span>one_plus_one<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>One plus one is 2</code></pre>
</div>
</div>
<p>A <strong>crucial concern with typecasting</strong> (the main reason we worry about it as data scientists) is that we need to ensure that <strong>the information we want to retain is indeed retained</strong> when we perform a typecasting operation, whether implicitly or explicitly.</p>
<p>For example, if we make a variable called <code>my_pi</code> which we’re hoping to use to represent <span class="math inline">\(\pi\)</span> to the maximum precision possible (e.g.&nbsp;for computing areas of circles), then we need to make sure that we never <strong>typecast</strong> its value to a numeric type like <code>int</code> that cannot represent the decimal precision necessary for using <span class="math inline">\(\pi\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>my_pi <span class="op">=</span> math.pi</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_pi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3.141592653589793</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>my_pi <span class="op">=</span> <span class="bu">int</span>(my_pi)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_pi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3</code></pre>
</div>
</div>
<p>This may seem like a silly example, since for values like <code>my_pi</code> we would usually be aware and careful about loss of precision, but it can become more and more easy to make these types of mistakes—where typecasting leads to a <strong>loss of information</strong>—when you are working with a large collection of numeric variables.</p>
<p>More formally, we can say that <strong>information is lost</strong> when typecasting a variable <code>x</code> into some other type to produce a new variable <code>y</code> if it would not be possible to recover the information contained in <code>x</code> from the new variable <code>y</code>. So, given this definition,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>my_int <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>my_str <span class="op">=</span> <span class="bu">str</span>(my_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Would <strong>not</strong> be a case where information is lost, since we could always recover the original <code>my_int</code> by typecasting <strong>back</strong> to the <code>int</code> type;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>my_new_int <span class="op">=</span> <span class="bu">int</span>(my_str)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_new_int, my_int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>my_new_int <span class="op">==</span> my_int</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>True</code></pre>
</div>
</div>
<p>However, in the following code block</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>my_float <span class="op">=</span> <span class="fl">3.14</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>my_int <span class="op">=</span> <span class="bu">int</span>(my_float)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have performed a typecasting operation which has resulted in a <strong>loss of information</strong>, since unlike in the previous example, we are unable to re-create the original <code>my_float</code> value by typecasting <code>my_int</code> back to the <code>float</code> type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>my_new_float <span class="op">=</span> <span class="bu">float</span>(my_int)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_float, my_new_float)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3.14 3.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>my_float <span class="op">==</span> my_new_float</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>False</code></pre>
</div>
</div>
</section>
<section id="typecasting-practice-problem" class="level3">
<h3 class="anchored" data-anchor-id="typecasting-practice-problem">Typecasting: Practice Problem</h3>
<ol type="1">
<li>Assume we have just created a variable <code>my_float</code> using the line <code>my_float = 3.14</code>. Which of the following Python expressions represents a <strong>typecasting</strong> operation where <strong>information is lost</strong>?
<ol type="a">
<li><code>my_int = int(my_float)</code></li>
<li><code>my_str = str(my_float)</code></li>
<li><code>my_float2 = float(my_float)</code></li>
<li><code>my_float3 = np.float64(my_float)</code></li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>a</strong>: When we convert from the <code>float</code> type to the <code>int</code> type, the decimal information from the <code>float</code> is <strong>lost</strong>, since the resulting <code>int</code> will contain only the non-decimal information from the <code>float</code>. So, for example, <code>int(3.14)</code> produces the <code>int</code> value <code>3</code>, <code>int(-10.001)</code> produces the <code>int</code> value <code>-10</code>, and so on.</p>
</div>
</div>
</div>
</section>
</section>
<section id="steps-in-the-data-science-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="steps-in-the-data-science-pipeline">Steps in the Data Science Pipeline</h2>
<section id="data-cleaning-overview" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-overview">Data Cleaning: Overview</h3>
<p>When talking about <strong>tabular datasets</strong> (as in, datasets which can be represented as tables, and hence as <code>DataFrame</code>s in Pandas or <code>tibble</code>s in Tidyverse), we call a dataset:</p>
<ul>
<li><strong>Long</strong> if the dataset contains <strong>multiple rows</strong> for each <strong>unit of observation</strong> in the data, and</li>
<li><strong>Wide</strong> if the dataset only contains <strong>one row</strong> for each <strong>unit of observation</strong> in the data.</li>
</ul>
<p>For example, if the unit of observation is a <strong>country</strong>, then the following dataset is in <strong>long</strong> format, since it contains <strong>two rows</strong> for each country:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>long_df <span class="ot">&lt;-</span> table2 <span class="sc">|&gt;</span> <span class="fu">filter</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    year <span class="sc">==</span> <span class="dv">2000</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">select</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    country, type, count</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">rename</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">variable =</span> type,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> count</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>long_df <span class="sc">|&gt;</span> <span class="fu">write_csv</span>(<span class="st">"assets/long_df.csv"</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>long_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: left;">variable</th>
<th style="text-align: right;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">2666</td>
</tr>
<tr class="even">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">20595360</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brazil</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">80488</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazil</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">174504898</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">213766</td>
</tr>
<tr class="even">
<td style="text-align: left;">China</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">1280428583</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>On the other hand, the following dataset (with the same unit of observation) is in <strong>wide</strong> format, since each country’s information is contained in one and only one row.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>wide_df <span class="ot">&lt;-</span> table1 <span class="sc">|&gt;</span> <span class="fu">filter</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    year <span class="sc">==</span> <span class="dv">2000</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">select</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    country, cases, population</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>wide_df <span class="sc">|&gt;</span> <span class="fu">write_csv</span>(<span class="st">"assets/wide_df.csv"</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>wide_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: right;">cases</th>
<th style="text-align: right;">population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">2666</td>
<td style="text-align: right;">20595360</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">80488</td>
<td style="text-align: right;">174504898</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: right;">213766</td>
<td style="text-align: right;">1280428583</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can use the Pandas function <code>pd.melt()</code>, however, to <strong>convert this second dataset from wide to long format</strong>, so it matches the format of the first dataset, as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>wide_df <span class="op">=</span> pd.read_csv(<span class="st">"assets/wide_df.csv"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>long_df <span class="op">=</span> pd.melt(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    wide_df,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    id_vars<span class="op">=</span>[<span class="st">'country'</span>],</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    value_vars<span class="op">=</span>[<span class="st">'cases'</span>,<span class="st">'population'</span>]</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>disp(long_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">country</th>
<th style="text-align: left;">variable</th>
<th style="text-align: right;">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">2666</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Brazil</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">80488</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">China</td>
<td style="text-align: left;">cases</td>
<td style="text-align: right;">213766</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">20595360</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Brazil</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">174504898</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">China</td>
<td style="text-align: left;">population</td>
<td style="text-align: right;">1280428583</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-cleaning-practice-problems" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-practice-problems">Data Cleaning: Practice Problems</h3>
<ol type="1">
<li><p>Consider the following dataset, where the unit of observation is a <strong>person</strong> on a mailing list:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>id</th>
<th>name</th>
<th>email</th>
<th>ip_address</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Jimmy Fishburn</td>
<td>jfishburn0@ask.com</td>
<td>10.14.177.175</td>
</tr>
<tr class="even">
<td>1</td>
<td>Chadwick Arrowsmith</td>
<td>carrowsmith1@photobucket.com</td>
<td>186.209.191.254</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Antony Hartington</td>
<td>ahartington2@constantcontact.com</td>
<td>200.241.210.61</td>
</tr>
</tbody>
</table>
<p>Is this dataset in <strong>long</strong> or <strong>wide</strong> format?</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This dataset is in <strong>wide</strong> format, since the unit of observation is a <strong>person</strong>, and each person is represented as a <strong>single row</strong> in the dataset, so that each column corresponds to a property of a single person.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><p>Consider the following dataset, where the unit of observation is again a <strong>person</strong> on mailing list:</p>
<table class="table">
<thead>
<tr class="header">
<th>id</th>
<th>variable</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>name</td>
<td>Jimmy Fishburn</td>
</tr>
<tr class="even">
<td>0</td>
<td>email</td>
<td><code>jfishburn0@ask.com</code></td>
</tr>
<tr class="odd">
<td>0</td>
<td>ip_address</td>
<td><code>10.14.177.175</code></td>
</tr>
<tr class="even">
<td>1</td>
<td>name</td>
<td>Chadwick Arrowsmith</td>
</tr>
<tr class="odd">
<td>1</td>
<td>email</td>
<td><code>carrowsmith1@photobucket.com</code></td>
</tr>
<tr class="even">
<td>1</td>
<td>ip_address</td>
<td><code>186.209.191.254</code></td>
</tr>
<tr class="odd">
<td>2</td>
<td>name</td>
<td>Antony Hartington</td>
</tr>
<tr class="even">
<td>2</td>
<td>email</td>
<td><code>ahartington2@constantcontact.com</code></td>
</tr>
<tr class="odd">
<td>2</td>
<td>ip_address</td>
<td>200.241.210.61</td>
</tr>
</tbody>
</table>
<p>Is this dataset in <strong>long</strong> or <strong>wide</strong> format?</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This dataset is in <strong>long</strong> format, since the unit of observation is a <strong>person</strong>, but the information we have about each person is <strong>spread over three rows</strong>.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li>What Pandas function could we use to transform the dataset from the first problem (the wide-format dataset) into the dataset from the previous problem (the long-format dataset)?
<ol type="a">
<li><code>pd.sort_values()</code></li>
<li><code>pd.melt()</code></li>
<li><code>pd.to_numeric()</code></li>
<li><code>pd.unique()</code></li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>a</strong>: <code>pd.melt()</code> is the function we use to transform wide-format datasets into long-format datasets, where we supply this function with an <code>id_vars</code> parameter telling it the column which <strong>uniquely identifies the unit of observation</strong> in the dataset.</p>
</div>
</div>
</div>
<p><strong>NOTE:</strong> For more details on the syntax of <code>pd.melt()</code> and other functions used for transforming data, please see my writeup on <a href="../melt-and-pivot/" target="_blank"><code>pd.melt()</code> and <code>pd.pivot()</code> here</a>.</p>
</section>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">EDA</h3>
<p>Exploratory Data Analysis or “EDA” is a broad term, describing what is essentially a toolkit of methods you can use to start to get an understanding of your data <strong>before</strong> you begin developing and testing hypotheses. Given this, on the midterm you may encounter questions about EDA like:</p>
<ul>
<li>Multiple-choice questions asking you whether a given technique would be considered an EDA or CDA (Confirmatory Data Analysis) step,</li>
<li>An essay question asking you to describe a few different examples of EDA techniques,</li>
<li>An essay question asking you to describe a single EDA technique in-depth, or</li>
<li>An essay question asking you to describe the differences between Exploratory Data Analysis and Confirmatory Data Analysis.</li>
</ul>
<p>An example multiple choice question would be one like the following question:</p>
<ol type="1">
<li>Which of the following techniques would <strong>not</strong> be considered part of the Exploratory Data Analysis (EDA) process:
<ol type="a">
<li>Outlier Detection</li>
<li>Data Transformation</li>
<li>Hypothesis Testing</li>
<li>Bivariate Analysis (Bivariate Plots and Cross-Tabulations)</li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>c</strong>: Hypothesis Testing is very specifically <strong>not</strong> part of the EDA process, since the idea of EDA is that we <strong>“explore”</strong> the data <strong>before</strong> we develop explicit hypotheses. It is on the basis of EDA that we <strong>then</strong> form hypotheses, using techniques from <strong>Confirmatory</strong> Data Analysis to <strong>evaluate</strong> these hypotheses on the basis of the available data.</p>
</div>
</div>
</div>
<p>Then, an example essay question could be as follows:</p>
<ol start="2" type="1">
<li>Explain the process of <strong>Outlier Detection</strong> in-depth, and why it is important with respect to the goals of <strong>Exploratory Data Analysis</strong> (<strong>EDA</strong>).</li>
</ol>
<p><em>(Here, just to be safe, I’m placing the solution in a static block, rather than an expand/collapse block, but you should try writing your own essay first before looking at the solution!)</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>An example short essay could be as follows:</p>
<p><strong>Outlier detection</strong> is the process of analyzing a dataset with respect to a hypothesized <strong>data-generating process</strong> (<strong>DGP</strong>) which is assumed to have generated the observed data, then identifying specific data points which are in the observed data yet would be <strong>unlikely to occur</strong> as a result of this data-generating process.</p>
<p>Although outlier detection is therefore always performed with respect to some model of how the observed data came about (the DGP), there are a set of <strong>widely-used heuristics</strong> which data scientists have found useful to use over the years, as simple “rules of thumb” for identifying these unlikely/extreme values without having to spend too much time worrying about the DGP for every variable.</p>
<p>The two most widely-used outlier detection methods are as follows:</p>
<ul>
<li><p>The <strong>Tukey Rule</strong>: This rule works for a wide range of data distributions and says that, if we have a set of <span class="math inline">\(n\)</span> values for some variable <span class="math inline">\(X\)</span>, <span class="math inline">\(\{x_1, x_2, \ldots, x_n\}\)</span>, then one of the values <span class="math inline">\(x_i\)</span> can be considered an <strong>outlier</strong> relative to the other values if the value of <span class="math inline">\(x_i\)</span> is less than <span class="math inline">\(1.5 \cdot Q_1\)</span> or more than <span class="math inline">\(1.5 \cdot Q_3\)</span>:</p>
<p><span class="math display">\[
  x_i \not\in [Q_1 - 1.5 \cdot IQR, \; Q_3 + 1.5 \cdot IQR],
  \]</span></p>
<p>where <span class="math inline">\(Q_1\)</span> is the first quartile of the data <span class="math inline">\(X\)</span> (the 25th percentile), <span class="math inline">\(Q_3\)</span> is the third quartile of the data <span class="math inline">\(X\)</span>, and <span class="math inline">\(IQR\)</span> is the <strong>interquartile range</strong>, defined as <span class="math inline">\(IQR = Q_3 - Q_1\)</span>.</p></li>
<li><p>The <strong>Three-Sigma Rule</strong>: This rule was specifically created as a “rule of thumb” for identifying outliers in <strong>normally-distributed</strong> data, but technically could be used for any set of values <span class="math inline">\(X = \{x_1, x_2, \ldots, x_n\}\)</span> for which we know the mean <span class="math inline">\(\mu_X\)</span> and standard deviation <span class="math inline">\(\sigma_X\)</span>.</p>
<p>The rule here is that a data point, in this case a particular value <span class="math inline">\(x_i\)</span>, is considered an <strong>outlier</strong> relative to the other values of <span class="math inline">\(X\)</span> if its value is <strong>more than three standard deviations away from the mean</strong>—that is, if</p>
<p><span class="math display">\[
  x_i \not\in [\mu_X - 3 \cdot \sigma_X, \; \mu_X + 3 \cdot \sigma_X].
  \]</span></p></li>
</ul>
<p>These two rules, along with other methods for detecting outliers, are important for the EDA process because our eventual <strong>Confirmatory</strong> Data Analysis can be <strong>inaccurate</strong>, skewed, biased, and so on, if there are erroneous values present in the data for a given variable.</p>
<p>For example, if a dataset represents the digitized version of a dataset of selling prices for a product which was originally compiled by hand, and the digitization failed to detect the hand-written <strong>decimal points</strong> for some of the prices in the data, then prices like $9.99 could be erroneously translated into <code>999</code>, skewing the values of these prices by two orders of magnitude, while prices like $10 or $20 would be unaffected. Outlier detection could thus potentially identify this issue, allowing the researcher to go in and manually fix the errors before moving to the Confirmatory Data Analysis and hypothesis testing stage.</p>
</div>
</div>
</div>
</section>
</section>
<section id="text-analysis" class="level2">
<h2 class="anchored" data-anchor-id="text-analysis">Text Analysis</h2>
<p>We also only had a small amount of time to cover text analysis and Natural Language Processing (NLP) techniques in class, but in this case we really only want you all to know some basics, since you can take an entire class after this one which is solely about NLP!</p>
<p>So, given the basic technique we talked about in class, of <strong>taking a corpus of texts and representing it as a <em>Document-Term Matrix</em> (DTM)</strong>, you should be able to answer the following multiple-choice question:</p>
<ol type="1">
<li><p>Assume we have four documents, <code>A.txt</code>, <code>B.txt</code>, <code>C.txt</code>, and <code>D.txt</code>, as follows:</p>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>A.txt</strong></pre>
</div>
<div class="sourceCode" id="cb33"><pre class="sourceCode txt code-with-copy"><code class="sourceCode default"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Green eggs are sweet.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>B.txt</strong></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="sourceCode txt code-with-copy"><code class="sourceCode default"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Ham is sour.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>C.txt</strong></pre>
</div>
<div class="sourceCode" id="cb35"><pre class="sourceCode txt code-with-copy"><code class="sourceCode default"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>Cats love sweet food.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="code-with-filename">
<div class="code-with-filename-file">
<pre><strong>D.txt</strong></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="sourceCode txt code-with-copy"><code class="sourceCode default"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Dogs love sour food.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Which of the following matrices represents the <strong>document-term matrix</strong> encoding these four documents (assuming that we have performed <strong>lowercasing</strong>, <strong>word tokenization</strong>, and <strong>stopword removal</strong> on each document before vectorizing it)?</p>
<p><em>(Note: The name for each table is contained in the upper-left-most cell of the table: since (A) appears in the upper-left-most cell of the first table below, for example, this table represents choice (A))</em></p></li>
</ol>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(A)</th>
<th><code>green</code></th>
<th><code>eggs</code></th>
<th><code>sweet</code></th>
<th><code>ham</code></th>
<th><code>sour</code></th>
<th><code>cats</code></th>
<th><code>love</code></th>
<th><code>food</code></th>
<th><code>dogs</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>A</code></td>
<td>4</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td><code>B</code></td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td><code>C</code></td>
<td>2</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td><code>D</code></td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(B)</th>
<th><code>green</code></th>
<th><code>eggs</code></th>
<th><code>sweet</code></th>
<th><code>ham</code></th>
<th><code>sour</code></th>
<th><code>cats</code></th>
<th><code>love</code></th>
<th><code>food</code></th>
<th><code>dogs</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>A</code></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>B</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td><code>C</code></td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>D</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(C)</th>
<th><code>green</code></th>
<th><code>eggs</code></th>
<th><code>sweet</code></th>
<th><code>ham</code></th>
<th><code>sour</code></th>
<th><code>cats</code></th>
<th><code>love</code></th>
<th><code>food</code></th>
<th><code>dogs</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>A</code></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>B</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td><code>C</code></td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>-1</td>
<td>-5</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>D</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>(D)</th>
<th><code>green</code></th>
<th><code>eggs</code></th>
<th><code>sweet</code></th>
<th><code>ham</code></th>
<th><code>sour</code></th>
<th><code>cats</code></th>
<th><code>love</code></th>
<th><code>food</code></th>
<th><code>dogs</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>A</code></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>B</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td><code>C</code></td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td><code>D</code></td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>(D)</strong>. We can tell that this final table is the correct DTM representation for our four documents by a process of elimination, for example:</p>
<ul>
<li>The first table (A) contains a value of <code>4</code> in the cell representing the count of the token <code>green</code> in document <code>A</code>, whereas document <code>A</code> in fact only contains the token <code>green</code> <strong>one time</strong>.</li>
<li>The second table (B) contains a value of <code>2</code> in the cell representing the count of the token <code>love</code> in document <code>A</code>, whereas document <code>A</code> in fact does not contain the token <code>love</code> at all.</li>
<li>The third table (C) contains <strong>negative values</strong>: for example, the cell representing the count of the token <code>sour</code> in document <code>C</code> has the value <code>-5</code>. Since documents cannot contain tokens a negative number of times, we know that this is an invalid DTM in general.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="machine-learning" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning">Machine Learning</h2>
<section id="types-of-learning-methods" class="level3">
<h3 class="anchored" data-anchor-id="types-of-learning-methods">Types of Learning Methods</h3>
<p>At a general level (so, for essay questions for example), we want you to understand the distinction between <strong>supervised</strong>, <strong>unsupervised</strong>, and <strong>reinforcement learning</strong>, as well as how the following terms relate to these three types of learning:</p>
<ul>
<li>Classes</li>
<li>Labels</li>
<li>Binary classification</li>
<li>Multiclass classification</li>
<li>Scalar regression</li>
<li>Vector regression</li>
</ul>
<p>So, for example, we could ask the following type of essay question to test your understanding of these terms and their interrelationships:</p>
<ol type="1">
<li>Describe how <strong>regression</strong> tasks differ from <strong>classification</strong> tasks in terms of Machine Learning, and then describe how we could <strong>transform</strong> the data we have for our regression task in such a way as to turn it into a <strong>classification</strong> task, and vice-versa. For example, imagine that the codebase at the company you’re working for only contains <strong>classification</strong> algorithms, so that you will be unable to learn anything about your data without being able to plug it into a classification algorithm, but all of the variables in the dataset are <strong>continuous</strong>. Then imagine that the codebase instead only contains <strong>regression</strong> algorithms, but that you have features and labels for a <strong>classification</strong> problem that you’d like to solve.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>An example response to this essay question could be as follows:</p>
<p><strong>Regression</strong> tasks differ from <strong>classification</strong> tasks, in Machine Learning, in that regression tasks involve discovering statistical relationships between a set of features and a <strong>continuous</strong> label variable, while classification tasks involve discovering statistical relationships between a set of features an a <strong>discrete</strong> label variable.</p>
<p>The following two mostly-similar examples illustrate this difference:</p>
<ul>
<li><strong>Classification task</strong>: Predict whether a review for a product will be a <strong>thumbs-up</strong> or <strong>thumbs-down</strong> review, on the basis of the text of the review</li>
<li><strong>Regression task</strong>: Predict the numeric score given to a product by a reviewer (where scores are allowed to be any number in the range <span class="math inline">\([0,100]\)</span>), on the basis of the text of the review.</li>
</ul>
<p>In the former case, our goal is to take the text of a review and use it to predict a <strong>binary label</strong> <span class="math inline">\(\ell\)</span> for this review from the set <span class="math inline">\(\{\text{thumbs up}, \text{thumbs down}\}\)</span>, whereas in the latter case our goal is to take the text of a review and use it to predict a <strong>real-valued score</strong> <span class="math inline">\(s\)</span> from the interval <span class="math inline">\([0,100]\)</span>.</p>
<p>Although both of these Machine Learning tasks present their own difficulties, we can often transform one type into the other type via a set of transformations.</p>
<p>For example, to transform a <strong>binary classification</strong> task into a <strong>regression</strong> task, we could ask the regression algorithm to try and predict a real-valued score <span class="math inline">\(s \in [0,1]\)</span>, interpret this number as a “confidence score”, and convert the real-valued prediction into a binary prediction <span class="math inline">\(\widehat{\ell}\)</span> of the true label <span class="math inline">\(\ell\)</span> by rounding to the nearest integer:</p>
<p><span class="math display">\[
\widehat{\ell}(s) = \begin{cases}
0 &amp;\text{if }s \leq 0.5, \\
1 &amp;\text{otherwise.}
\end{cases}
\]</span></p>
<p>Conversely, we can transform <strong>regression</strong> tasks into <strong>classification</strong> tasks by <strong>binning</strong> the continuous values into discrete bins.</p>
<p>For example, if we have a dataset with <strong>continuous labels</strong> representing scores <span class="math inline">\(s \in [0,100]\)</span>, we could convert these labels into discrete values by <strong>dividing the range <span class="math inline">\([0,100]\)</span> into three equal bins</strong>, calling values in <span class="math inline">\(\left[0,\frac{1}{3}\right)\)</span> “low” values, values in <span class="math inline">\(\left[ \frac{1}{3}, \frac{2}{3} \right]\)</span> “medium” values, and values in <span class="math inline">\(\left( 2/3, 1 \right]\)</span> “high” values. We could then give all “low” values the label <span class="math inline">\(0\)</span>, all “medium” values the label <span class="math inline">\(1\)</span>, and all “high” values the label <span class="math inline">\(2\)</span>, producing the following mapping from continuous labels (appropriate for regression algorithms) to discrete labels <span class="math inline">\(\ell\)</span> (appropriate for classification algorithms):</p>
<p><span class="math display">\[
\ell(s) = \begin{cases}
0 &amp;\text{if }0 \leq x \leq \frac{1}{3}, \\
1 &amp;\text{if }\frac{1}{3} \leq x \leq \frac{2}{3}, \\
2 &amp;\text{if }\frac{2}{3} \leq x \leq 1.
\end{cases}
\]</span></p>
<p>And now we could use a <strong>multi-class classification algorithm</strong> (as opposed to a <strong>binary</strong> classification algorithm, which only works for labels with two possible values) to predict low, medium, or high score values. Then, if we really needed to guess a <strong>continuous</strong> value, we could guess the <strong>midpoint</strong> of each interval, so that the following function could map the predictions <span class="math inline">\(\widehat{\ell}_i\)</span> made by our multi-class classification algorithm back into continuous values <span class="math inline">\(\widehat{s}_i \in [0,100]\)</span>:</p>
<p><span class="math display">\[
\widehat{s}_i = \begin{cases}
\frac{1}{6} &amp;\text{if }\widehat{\ell}_i = 0, \\
\frac{1}{2} &amp;\text{if }\widehat{\ell}_i = 1, \\
\frac{5}{6} &amp;\text{if }\widehat{\ell}_i = 2.
\end{cases}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="distance-metrics" class="level3">
<h3 class="anchored" data-anchor-id="distance-metrics">Distance Metrics</h3>
<p>The main things to know here are (a) the various names for different distance metrics, and (b) the Machine Learning settings within which these various metrics <strong>are</strong> and <strong>are not appropriate</strong> to use.</p>
<p>So, some example multiple choice problems would be as follows:</p>
<ol type="1">
<li><p>You have a set of labeled data <span class="math inline">\((\mathbf{X}, \mathbf{y})\)</span>, and you are trying to train a machine learning algorithm to predict a <strong>probability distribution</strong> over the outcome <span class="math inline">\(Y_i\)</span> as a function of the features <span class="math inline">\(X_i\)</span>. Which of the following is the most appropriate <strong>distance metric</strong> to use as the <strong>loss function for a single prediction</strong> made by the algorithm, during training?</p>
<ol type="a">
<li>Edit Distance</li>
<li>Euclidean Distance</li>
<li>Kullback-Leibler Divergence</li>
<li>Cosine Distance</li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>c</strong>, Kullback-Leibler Divergence. While the other metrics are meant to handle different data types:</p>
<ul>
<li>Edit distance is a metric created to quantify the distance between <strong>strings</strong> in terms of how frequently they differ by character</li>
<li>Euclidean distance is a metric created to quantify the <strong>straight-line distance</strong> between points in a geometric space</li>
<li>Cosine distance is a metric created to quantify the <strong>angle</strong> between two vectors in a vector space</li>
</ul>
<p>The <strong>KL Divergence</strong> is a metric created specifically to quantify differences between two <strong>probability distributions</strong>, the situation we have in this question.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><p>You have a set of labeled data <span class="math inline">\((\mathbf{X}, \mathbf{y})\)</span>, where both <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(\mathbf{y}\)</span> may be extremely high-dimensional, and you are trying to train a machine learning algorithm to predict label values <span class="math inline">\(y_i\)</span> for given feature vectors <span class="math inline">\(X_i\)</span>.</p>
<p>Your goal is specifically to <strong>minimize the maximum distance between the predicted label <span class="math inline">\(\widehat{y_i}\)</span> and the true label <span class="math inline">\(y_i\)</span> across all dimensions</strong>.</p>
<p>For example:</p>
<ul>
<li>You want to penalize your algorithm heavily for predicting <span class="math inline">\(\widehat{y_i} = (3,0,0)\)</span> when the true label is <span class="math inline">\(y_i = (0,0,0)\)</span>, since in this case even though it perfectly guessed the second and third value of the vector <span class="math inline">\(y_i\)</span>, its guess for the first “coordinate” of <span class="math inline">\(y_i\)</span> was 3 units away from the true value</li>
<li>But, you don’t want to penalize it as heavily for predicting <span class="math inline">\(\widehat{y_i} = (-0.1, 1.0, 0.2)\)</span> when the true label is <span class="math inline">\(y_i = (0,0,0)\)</span>, since in this case its maximum error across all dimensions was <span class="math inline">\(1.0\)</span>.</li>
<li>Since the “worst” guess in the latter case was only <span class="math inline">\(1.0\)</span> units away from the true value, while the “worst” guess in the former case was <span class="math inline">\(3.0\)</span> units away from the true value, we would want to penalize the guess in the first case <strong>three times more heavily</strong> than the guess in the second case.</li>
</ul>
<p>What is the most appropriate distance metric to use as the <strong>loss function for a single prediction</strong> of the machine learning algorithm, in this case?</p>
<ol type="a">
<li>Euclidean Distance</li>
<li>Kullback-Leibler Divergence</li>
<li>The <span class="math inline">\(L^\infty\)</span>-Norm <span class="math inline">\(|| \widehat{y_i} - y_i ||_{\infty}\)</span></li>
<li>The <span class="math inline">\(L^1\)</span>-Norm <span class="math inline">\(|| \widehat{y_i} - y_i ||_1\)</span></li>
</ol></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Solution (Click to expand)">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution (Click to expand)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The correct answer is <strong>c</strong>, the <span class="math inline">\(L^\infty\)</span> norm, which can be seen more easily if we write it out as the norm which results from taking the <span class="math inline">\(L^p\)</span>-norm in general and computing its limit as <span class="math inline">\(p\)</span> goes to <span class="math inline">\(\infty\)</span>:</p>
<p><span class="math display">\[
\lim_{p \rightarrow \infty} || \widehat{y_i} - y_i || = \max_i\{\widehat{y_{i,1}} - y_{i,1}, \widehat{y_{i,2}} - y_{i,2}, \ldots, \widehat{y_{i,N}} - y_{i,N}\}.
\]</span></p>
<p>And so we see that, unlike the other distance metric choices, the <span class="math inline">\(L^\infty\)</span> norm specifically will penalize the machine learning algorithm’s guess <strong>in proportion to the maximum of the errors across all dimensions of <span class="math inline">\(y_i\)</span></strong>.</p>
</div>
</div>
</div>
</section>
<section id="precision-recall-f1-score" class="level3">
<h3 class="anchored" data-anchor-id="precision-recall-f1-score">Precision, Recall, F1 Score</h3>
</section>
<section id="loss-functions" class="level3">
<h3 class="anchored" data-anchor-id="loss-functions">Loss Functions</h3>
<ul>
<li><p>Loss functions: MSE, RMSE, MAE</p></li>
<li><p>Confusion matrix</p></li>
<li><p>Overfitting</p></li>
<li><p>KNN for classification and/or regression</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>