<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-11-03">

<title>DSAN 5000 – thor_eda_with_seaborn</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ETYTX4E16L"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ETYTX4E16L', { 'anonymize_ip': true});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script><script src="../../jjcustom.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lab-background" id="toc-lab-background" class="nav-link active" data-scroll-target="#lab-background">(1) Lab Background</a>
  <ul class="collapse">
  <li><a href="#the-vietnam-second-indochinese-war" id="toc-the-vietnam-second-indochinese-war" class="nav-link" data-scroll-target="#the-vietnam-second-indochinese-war">(1.1) The Vietnam / Second Indochinese War</a></li>
  <li><a href="#the-role-of-data-science-in-the-devastation" id="toc-the-role-of-data-science-in-the-devastation" class="nav-link" data-scroll-target="#the-role-of-data-science-in-the-devastation">(1.2) The Role of Data Science in the Devastation</a></li>
  <li><a href="#eda-and-bayesian-statistics-challenging-prior-beliefs-to-derive-posterior-beliefs" id="toc-eda-and-bayesian-statistics-challenging-prior-beliefs-to-derive-posterior-beliefs" class="nav-link" data-scroll-target="#eda-and-bayesian-statistics-challenging-prior-beliefs-to-derive-posterior-beliefs">(1.3) EDA and Bayesian Statistics: Challenging Prior Beliefs to Derive Posterior Beliefs</a></li>
  <li><a href="#dataset-info" id="toc-dataset-info" class="nav-link" data-scroll-target="#dataset-info">(1.4) Dataset Info</a></li>
  </ul></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data">(2) Loading the Data</a></li>
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data">(3) Missing Data</a></li>
  <li><a href="#different-formats-within-the-same-column" id="toc-different-formats-within-the-same-column" class="nav-link" data-scroll-target="#different-formats-within-the-same-column">(4) Different Formats Within The Same Column</a>
  <ul class="collapse">
  <li><a href="#the-ambiguous-object-type" id="toc-the-ambiguous-object-type" class="nav-link" data-scroll-target="#the-ambiguous-object-type">(4.1) The Ambiguous <code>object</code> Type</a></li>
  <li><a href="#splitting-the-column-into-parts" id="toc-splitting-the-column-into-parts" class="nav-link" data-scroll-target="#splitting-the-column-into-parts">(4.2) Splitting The Column Into Parts</a></li>
  </ul></li>
  <li><a href="#collapsing-messy-categorical-variables-into-clean-ones" id="toc-collapsing-messy-categorical-variables-into-clean-ones" class="nav-link" data-scroll-target="#collapsing-messy-categorical-variables-into-clean-ones">(5) Collapsing Messy Categorical Variables Into Clean Ones</a></li>
  <li><a href="#tabulation-and-cross-tabulation" id="toc-tabulation-and-cross-tabulation" class="nav-link" data-scroll-target="#tabulation-and-cross-tabulation">(6) Tabulation and Cross-Tabulation</a>
  <ul class="collapse">
  <li><a href="#summary-statistics-table-.describe" id="toc-summary-statistics-table-.describe" class="nav-link" data-scroll-target="#summary-statistics-table-.describe">(6.1) Summary Statistics Table: <code>.describe()</code></a></li>
  <li><a href="#cross-tabulation-of-the-relationship-between-two-variables" id="toc-cross-tabulation-of-the-relationship-between-two-variables" class="nav-link" data-scroll-target="#cross-tabulation-of-the-relationship-between-two-variables">(6.2) Cross-Tabulation of the Relationship Between Two Variables</a></li>
  </ul></li>
  <li><a href="#seaborn-time" id="toc-seaborn-time" class="nav-link" data-scroll-target="#seaborn-time">(7) Seaborn Time!</a>
  <ul class="collapse">
  <li><a href="#aggregation" id="toc-aggregation" class="nav-link" data-scroll-target="#aggregation">(7.1) Aggregation</a></li>
  <li><a href="#categorical-plots-with-catplot" id="toc-categorical-plots-with-catplot" class="nav-link" data-scroll-target="#categorical-plots-with-catplot">(7.2) Categorical Plots with <code>catplot()</code></a></li>
  <li><a href="#plotting-non-aggregated-data" id="toc-plotting-non-aggregated-data" class="nav-link" data-scroll-target="#plotting-non-aggregated-data">(7.3) Plotting Non-Aggregated Data</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploratory Data Analysis of the THOR Dataset in Seaborn</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Extra Writeups</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 3, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Colab Link">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Colab Link
</div>
</div>
<div class="callout-body-container callout-body">
<center>
<p><a href="https://colab.research.google.com/drive/1dfjh-y01PzMoLy647XzPSG1VcI8-7IFp" target="_blank"><img src="images/colab-badge.svg" class="img-fluid"><br>Click here to <strong>open in Colab</strong></a></p>
</center>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Accompanying Video">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Accompanying Video
</div>
</div>
<div class="callout-body-container callout-body">
<p>The recording of me going through each step of this writeup in order is now available <a href="https://georgetown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e8a47e6f-6b57-4728-80a6-b08e003d4439" target="_blank">here</a>. <strong>Because of the length</strong> of the video, please don’t think of it as something you need to watch from start to finish. Instead you can just use it as a resource where, if you encounter something in the writeup that you don’t understand, or if there is a particular cleaning step / plot that you want more information about, you can jump directly to that portion of the video.</p>
</div>
</div>
<section id="lab-background" class="level2">
<h2 class="anchored" data-anchor-id="lab-background">(1) Lab Background</h2>
<section id="the-vietnam-second-indochinese-war" class="level3">
<h3 class="anchored" data-anchor-id="the-vietnam-second-indochinese-war">(1.1) The Vietnam / Second Indochinese War</h3>
<blockquote class="blockquote">
<p>A massive bombing campaign in Cambodia. Anything that flies on anything that moves.<br>–Henry Kissinger, US National Security Advisor, <a href="https://www.nytimes.com/2004/05/27/us/kissinger-tapes-describe-crises-war-and-stark-photos-of-abuse.html" target="_blank">Dec.&nbsp;9, 1970</a>.</p>
</blockquote>
<p>In 1965, the United States launched <em>Operation Rolling Thunder</em>, a years-long aerial assault on Vietnam which devastated the country and its people (killing <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2440905/" target="_blank">over 3 million</a>), irreversably damaging its environment (with more extensive use of <a href="https://www.nytimes.com/2017/11/24/opinion/vietnam-the-chemical-war.html" target="_blank">chemical weapons</a> like Napalm than in any war before or since), its crops and forests (with 19 million gallons of <a href="https://www.history.com/news/agent-orange-wasnt-the-only-deadly-chemical-used-in-vietnam" target="_blank">Agent Orange</a> sprayed over 500,000 acres of crops and 5 million acres of forests), and its infrastructure. As a campaign of genuinely unprecedented ferocity and destruction launched by a military superpower against a poor, mostly rural/agrarian country (only 20% of its citizens lived in cities at the time), its <a href="https://jjacobs.me/mdb/chomsky-hr2/" target="_blank">devastating effects</a> are <strong>still felt to this day</strong> by those in Vietnam, Laos, and Cambodia.</p>
<p><em>(All of which is all my not-so-subtle chance to plug, before moving onto the data analysis, the <a href="https://www.halousa.org/get-involved/give/donate/" target="_blank">donation page</a> for the HALO Trust: an org headquartered right here in NW DC which is leading the worldwide effort to defuse unexploded landmines in these countries, where for example <strong>50,000 Laotians</strong> have been killed by these mines since the war “officially” ended)</em></p>
</section>
<section id="the-role-of-data-science-in-the-devastation" class="level3">
<h3 class="anchored" data-anchor-id="the-role-of-data-science-in-the-devastation">(1.2) The Role of Data Science in the Devastation</h3>
<p>As an example of a war where modern <strong>science and technology</strong> was seen as a central military resource (with chemistry research leading to the deployment of Agent Orange and Napalm, computer science research used to track and target individuals via early instances of <strong>machine learning models</strong>, and social science research used to e.g.&nbsp;justify driving villagers from their homes into concentration camps called “Strategic Hamlets”), it is an important piece of history for data scientists to grapple with: how the technologies we develop <strong>could</strong> be used to help people, but <strong>also</strong> could be used to inflict unimaginable horrors upon millions of innocent civilians. <strong>Datasets</strong> pertaining to this war, many of which have only become publicly/easily-available in the past few years, provide the perfect opportunity to use data science itself to study this example of a military “data science project” of a prior generation.</p>
</section>
<section id="eda-and-bayesian-statistics-challenging-prior-beliefs-to-derive-posterior-beliefs" class="level3">
<h3 class="anchored" data-anchor-id="eda-and-bayesian-statistics-challenging-prior-beliefs-to-derive-posterior-beliefs">(1.3) EDA and Bayesian Statistics: Challenging Prior Beliefs to Derive Posterior Beliefs</h3>
<p>Although the entire point of EDA in theory is to go in “without any assumptions” (but see below/slides), I’ll give a quick summary of the impression(s) I came away with after the cleaning, tabulating, and visualizing below, in combination with what I knew about it beforehand, so (a) you know what to expect going in and/or (b) so you can use it as a “prior” that you update while working through the visualizations (challenging received assumptions, rather than pretending we have none, should be the goal of EDA imo!)</p>
<p>Briefly: although <em>Operation Rolling Thunder</em> is often cited as the beginning of what people in the <strong>US</strong> usually call the <strong>“Vietnam War”</strong>, by looking at the basic collection of tabulations and visualizations herein it slowly emerges that probably the <em>most</em> horrifying and unprecedented destruction was experienced not even by those in Vietnam itself but by those in <strong>Laos</strong> over the timespan represented in the dataset (and, after a US-sponsored coup in 1970, <strong>Cambodia</strong> as well). I knew beforehand, for example, that Laos was the most-bombed (per square meter) territory in history, but in terms of the goals of EDA I definitely found my priors about the Vietnam War challenged by what the tables/plots seemed to be “saying” about the underlying historical event.</p>
<p>As a final piece of information to have as part of your prior knowledge, though, before we dive in: Keep in mind that although the numbers we’ll be examining are mostly in <strong>absolute</strong> units such as the <strong>number</strong> of bombings, they should be interpreted in the <strong>context</strong> of the relative populations of each country in the dataset, at the beginning of the campaign:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Country</th>
<th>Population</th>
<th>Year</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cambodia</td>
<td>6.2 million</td>
<td>1965</td>
<td><a href="https://databank.worldbank.org/source/population-estimates-and-projections?savedlg=1&amp;l=en" target="_blank">World Bank</a></td>
</tr>
<tr class="even">
<td>Laos</td>
<td>2.4 million</td>
<td>1965</td>
<td><a href="https://databank.worldbank.org/source/population-estimates-and-projections?savedlg=1&amp;l=en" target="_blank">World Bank</a></td>
</tr>
<tr class="odd">
<td>Democratic Republic of Vietnam<br>(North Vietnam)</td>
<td>17.7 million</td>
<td>1965</td>
<td><a href="https://www.documentcloud.org/documents/22435664-economic-intelligence-statistical-handbook-1966" target="_blank">CIA Intelligence Report</a> (via CREST), 1966, p.&nbsp;26</td>
</tr>
<tr class="even">
<td>Republic of Vietnam<br>(South Vietnam)</td>
<td>16 million</td>
<td>End of 1964</td>
<td><a href="https://www.intelligence.gov/assets/documents/tet-documents/cia/THE%20MANPOWER%20SITUATION%20IN_15472910_.pdf" target="_blank">CIA Intelligence Report</a> (via CREST), 1968, p.&nbsp;11</td>
</tr>
</tbody>
</table>
</section>
<section id="dataset-info" class="level3">
<h3 class="anchored" data-anchor-id="dataset-info">(1.4) Dataset Info</h3>
<p>The dataset we’ll be analyzing is called the <a href="https://data.world/datamil/vietnam-war-thor-data" target="_blank"><em>Vietnam War Theater History of Operations</em> (<strong>THOR</strong>) dataset</a>, released by the US Department of Defense in 2015. The raw data is too large (~1.5GB) to easily download and work with, so I’ll be using a reduced-form version below, but the full dataset is available at the previous link (from <code>data.world</code>).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
</section>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">(2) Loading the Data</h2>
<p>As you should slowly be getting in the habit of doing, we start by importing:</p>
<ul>
<li><strong>Pandas</strong> (for dataset storage and manipulation),</li>
<li><strong>NumPy</strong> (for any mathematical transformations we might want to apply), and</li>
<li><strong>Seaborn</strong> (for visualization, whether EDA-focused or otherwise)</li>
</ul>
<div id="cell-5" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:21.088562Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:21.070625Z&quot;}" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next we <strong>download the dataset</strong>. Technically Pandas’ <code>read_csv()</code> function does support URL arguments, so that we could load the dataset directly into Pandas via URL, but since we often open and close notebooks, or Jupyter crashes, to avoid re-downloading each time you can run the following line, which should download the <code>.csv</code> file into the same directory as wherever this notebook is stored (on Colab, for example, the same portion of your Google Drive that Colab allocates for the storage of the notebook).</p>
<p>Since we’ve already used Python’s <code>requests</code> library before, for data scraping, we’ll use that here to quickly request and save the file:</p>
<div id="cell-7" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:25.121460Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:22.234132Z&quot;}" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>thor_url <span class="op">=</span> <span class="st">"https://jpj.georgetown.domains/dsan5000-scratch/eda/thor_strikes.csv"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"thor_strikes.csv"</span>, <span class="st">'wb'</span>) <span class="im">as</span> outfile:</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  csv_content <span class="op">=</span> requests.get(thor_url, stream<span class="op">=</span><span class="va">True</span>).content</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  outfile.write(csv_content)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If the download was successful, you should have a <code>thor_strikes.csv</code> file in the same folder as this notebook (in Colab you can check the file tab in the sidebar on the left side of the page). We can then use <code>pd.read_csv()</code> to load the <code>.csv</code>-formatted dataset, and we can re-load the dataset again in the future without having to worry about re-downloading it.</p>
<div id="cell-9" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:25.613302Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:25.123359Z&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>strike_df <span class="op">=</span> pd.read_csv(<span class="st">"thor_strikes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another good habit you can get into is always checking the output of the <code>.head()</code> function after loading the dataset, just to make sure that everything loaded as you expected. It usually doesn’t (😅)</p>
<div id="cell-11" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:25.632636Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:25.615858Z&quot;}" data-outputid="85baa4da-2d65-4c49-92c4-7c227d619a4f" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>strike_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MFUNC_DESC</th>
<th data-quarto-table-cell-role="th">MISSIONID</th>
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">THOR_DATA_VIET_ID</th>
<th data-quarto-table-cell-role="th">MSNDATE</th>
<th data-quarto-table-cell-role="th">SOURCEID</th>
<th data-quarto-table-cell-role="th">NUMWEAPONSDELIVERED</th>
<th data-quarto-table-cell-role="th">TGTTYPE</th>
<th data-quarto-table-cell-role="th">TGTLATDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">TGTLONDDD_DDD_WGS84</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>STRIKE</td>
<td>1047</td>
<td>LAOS</td>
<td>4</td>
<td>1970-02-02</td>
<td>642780</td>
<td>2</td>
<td>TRUCKS</td>
<td>16.902500</td>
<td>106.014166</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>STRIKE</td>
<td>1407</td>
<td>LAOS</td>
<td>6</td>
<td>1970-11-25</td>
<td>642782</td>
<td>6</td>
<td>AAA\37MM CR MORE</td>
<td>19.602222</td>
<td>103.597222</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>STRIKE</td>
<td>9064</td>
<td>LAOS</td>
<td>7</td>
<td>1972-03-08</td>
<td>642783</td>
<td>0</td>
<td>TRUCKS</td>
<td>14.573611</td>
<td>106.689722</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>STRIKE</td>
<td>8630</td>
<td>LAOS</td>
<td>16</td>
<td>1971-05-12</td>
<td>642792</td>
<td>4</td>
<td>TRK\PRK\STORE AREA</td>
<td>17.563611</td>
<td>105.756666</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>STRIKE</td>
<td>1391</td>
<td>LAOS</td>
<td>18</td>
<td>1971-12-19</td>
<td>642794</td>
<td>0</td>
<td>PERSONNEL\ANY</td>
<td>16.864166</td>
<td>105.349166</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>In our case, though, the output looks pretty much as expected, in terms of Pandas being able to automatically detect the header row and the splits between columns. So, let’s move on to the EDA!</p>
</section>
<section id="missing-data" class="level2">
<h2 class="anchored" data-anchor-id="missing-data">(3) Missing Data</h2>
<p>First things first, before we worry about missing data itself, we should think about <strong>which variables we want to analyze</strong>, since for now we can just worry about checking for missing values within the columns corresponding to these variables.</p>
<p>The <strong>official 59-page codebook for the dataset</strong>, an absolutely crucial thing to have on hand during any data analysis, <a href="https://jpj.georgetown.domains/dsan5000-scratch/eda/THOR%20Draft%20Data%20Dictionary%20Dec%202016.pdf" target="_blank">can be found at this link</a>. To skip over you having to read a 59-page document, though, I’ll now introduce a shortened, simplified codebook.</p>
<p>In our case, since we’re doing <strong>exploratory</strong> data analysis, in theory we shouldn’t have any hypotheses in mind yet. In reality we <strong>do</strong> have hypotheses in our heads, subconsciously at least, so when I say that I just mean that we’re not directly trying to <strong>confirm</strong> or <strong>deny</strong> these hypotheses at this stage. We are just hoping to <strong>question</strong>/<strong>interrogate</strong> them as we go along…</p>
<p>Keep in mind Tukey’s metaphor, that:</p>
<ul>
<li><strong>EDA = detective work</strong>, collecting evidence for a future trial, while</li>
<li><strong>CDA = the trial itself</strong>!</li>
</ul>
<p>I’m just going to focus on a few key variables which are central to understanding the processes underlying the data (the destruction of the countries across former Indochina). Let’s also think about <strong>what type of data</strong> each column represents—categorical vs.&nbsp;numeric, ordinal vs.&nbsp;cardinal, etc. Just like in the lab we can then use this info, as recorded in the following table, as our <strong>codebook</strong> for understanding what each variable represents:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th>Description</th>
<th>Variable Type</th>
<th>Datatype</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>TGTCOUNTRY</code></td>
<td>This should tell us, for a given strike, the <strong>country</strong> within whose borders the strike was carried out.</td>
<td>Categorical</td>
<td><code>string</code></td>
</tr>
<tr class="even">
<td><code>MSNDATE</code></td>
<td>This should tell us the <strong>date</strong> (in Y/M/D format) that the strike was carried out.</td>
<td>Discrete numeric (date)</td>
<td><strong><code>object</code></strong>(!) (see below)</td>
</tr>
<tr class="odd">
<td><code>TGTTYPE</code></td>
<td>This should tell us the <strong>type</strong> of target, e.g., whether it was a vehicle, a group of people, an individual person, etc.</td>
<td>Categorical</td>
<td><code>string</code></td>
</tr>
<tr class="even">
<td><code>TGTLATDD_DDD_WGS84</code></td>
<td>The <strong>latitude</strong> coordinate of the target</td>
<td>Continuous</td>
<td><code>float</code></td>
</tr>
<tr class="odd">
<td><code>TGTLONDD_DDD_WGS84</code></td>
<td>The <strong>longitude</strong> coordinate of the target</td>
<td>Continuous</td>
<td><code>float</code></td>
</tr>
</tbody>
</table>
<p>As our first EDA task, let’s look into the first variable in the table above: <code>TGTCOUNTRY</code>. As the section header suggests, we’re going to see if this column has any <strong>missing data</strong> and, if so, what the missing data means and what to do about it.</p>
<p><strong>[Crucial point here:]</strong> If we started using Pandas methods with their default arguments, we might get to thinking that nothing is wrong here, and move on from missing data checks… Take a look at what the <code>value_counts()</code> function returns when we use this function to look at the distribution of values in <code>TGTCOUNTRY</code> without including any additional parameters:</p>
<div id="cell-16" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:28.000089Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:27.997177Z&quot;}" data-outputid="8899c271-cecb-45c0-974b-6c8456ade526" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'TGTCOUNTRY'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>TGTCOUNTRY
LAOS              690161
NORTH VIETNAM     245977
SOUTH VIETNAM      54253
CAMBODIA           13271
THAILAND             146
UNKNOWN               23
WESTPAC WATERS         6
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>All seems well from this table: we might think “ok, great, they have encoded the 23 missing values from the original non-digitized data as <code>"UNKNOWN"</code>, and all the other values are interpretable non-missing labels, so we’re good right?”</p>
<p>Sadly we’re <strong>NOT GOOD 😭</strong>. Let’s check one more thing, to slowly move towards the hidden issue here. Let’s start by <strong>summing up</strong> the counts that <code>value_counts()</code> has given us for each value:</p>
<div id="cell-18" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:29.079885Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:29.074421Z&quot;}" data-outputid="9613d968-5dc7-4d11-c1cd-3041827a76be" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>value_counts_sum <span class="op">=</span> strike_df[<span class="st">'TGTCOUNTRY'</span>].value_counts().<span class="bu">sum</span>()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>value_counts_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>1003837</code></pre>
</div>
</div>
<p>Next let’s take a look at the total number of rows and columns in our <code>DataFrame</code>, by checking the <code>shape</code> attribute</p>
<p>[Here it’s important to note that, unlike most of the other attributes that we use to analyze <code>DataFrame</code> objects, <code>shape</code> is <strong>not a function</strong> but a <strong>static variable</strong>, an <strong>attribute</strong> of the <code>DataFrame</code> object. That’s why we just use <code>.shape</code> rather than <code>.shape()</code> to access this information.]</p>
<div id="cell-20" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:29.568829Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:29.542024Z&quot;}" data-outputid="15f07c7b-665d-4ef0-fc74-d528ac722b85" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>num_rows <span class="op">=</span> strike_df.shape[<span class="dv">0</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>num_rows</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>1007674</code></pre>
</div>
</div>
<p>Do you see the issue? If not, let’s check the difference between these two values:</p>
<div id="cell-22" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:30.191209Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:30.155395Z&quot;}" data-outputid="b27b8b4c-5e1d-45c7-d15f-05b9ec1e7c8d" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>num_rows <span class="op">-</span> value_counts_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>3837</code></pre>
</div>
</div>
<p>This tells us, to our horror, that there are <strong>3,837</strong> rows in our <code>DataFrame</code> which are completely unaccounted-for in the output produced by <code>value_counts()</code> 😰</p>
<p>And the reason is, as it turns out, the <code>value_counts()</code> function <strong>excludes missing values</strong> by default, so that the above output actually tells us <strong>absolutely nothing</strong> about whether or not there are missing values in the column! Scary stuff.</p>
<p>There is an easy fix, however: we can just include the <code>dropna = False</code> argument in our call to the <code>value_counts()</code> function, which will override this default behavior and show missing values as one of the possible values in the table of counts:</p>
<div id="cell-24" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:30.759370Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:30.752596Z&quot;}" data-outputid="81a9be2e-e68b-4fe9-d63b-974f28aa7f08" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'TGTCOUNTRY'</span>].value_counts(dropna <span class="op">=</span> <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>TGTCOUNTRY
LAOS              690161
NORTH VIETNAM     245977
SOUTH VIETNAM      54253
CAMBODIA           13271
NaN                 3837
THAILAND             146
UNKNOWN               23
WESTPAC WATERS         6
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>And now we see that, in fact, there are <strong>thousands of strikes</strong> for which no target country was recorded in the dataset: about <strong>167 times more missing data</strong> than we originally thought when we only saw that 23 of the rows had a <code>TGTCOUNTRY</code> value of <code>"UNKNOWN"</code>.</p>
<p>So, what can we do about this? In later weeks of the course and/or in later weeks of DSAN5100 we’ll learn about some more advanced methods for <strong>inputing missing values</strong>, for example by <strong>explicitly modeling the data-generating process</strong> that led some of the values to be missing. Until we know how to do that, however, for the sake of moving on with the EDA we will ignore these rows when we move onto other EDA tasks, <strong>keeping in mind that this is NOT acceptable practice in general for data science, outside of tutorial examples like this!!</strong></p>
<p>Before we move to those tasks, however, let’s quickly look at how we can visualize the <strong>distribution of missing values</strong> in this column (along with the other columns), using the third-party <a href="https://libraries.io/pypi/missingno" target="_blank"><code>missingno</code> package</a> mentioned in the lab instructions!</p>
<div id="cell-27" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:32.716065Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:31.637272Z&quot;}" data-outputid="a5ce37da-9ad9-42d4-be8d-b33dbaff532c" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install missingno</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: missingno in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (0.5.2)
Requirement already satisfied: numpy in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from missingno) (1.26.0)
Requirement already satisfied: matplotlib in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from missingno) (3.8.0)
Requirement already satisfied: scipy in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from missingno) (1.11.2)
Requirement already satisfied: seaborn in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from missingno) (0.12.2)
Requirement already satisfied: contourpy&gt;=1.0.1 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (1.1.1)
Requirement already satisfied: cycler&gt;=0.10 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (0.11.0)
Requirement already satisfied: fonttools&gt;=4.22.0 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (4.42.1)
Requirement already satisfied: kiwisolver&gt;=1.0.1 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (1.4.5)
Requirement already satisfied: packaging&gt;=20.0 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (23.1)
Requirement already satisfied: pillow&gt;=6.2.0 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (10.0.1)
Requirement already satisfied: pyparsing&gt;=2.3.1 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (3.1.1)
Requirement already satisfied: python-dateutil&gt;=2.7 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from matplotlib-&gt;missingno) (2.8.2)
Requirement already satisfied: pandas&gt;=0.25 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from seaborn-&gt;missingno) (2.1.0)
Requirement already satisfied: pytz&gt;=2020.1 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pandas&gt;=0.25-&gt;seaborn-&gt;missingno) (2023.3.post1)
Requirement already satisfied: tzdata&gt;=2022.1 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pandas&gt;=0.25-&gt;seaborn-&gt;missingno) (2023.3)
Requirement already satisfied: six&gt;=1.5 in /Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from python-dateutil&gt;=2.7-&gt;matplotlib-&gt;missingno) (1.16.0)</code></pre>
</div>
</div>
<p>I don’t want to give away the answer to this portion of the lab by producing a missing-data matrix directly, so instead I will use a different but still very helpful function from <code>missingno</code>, the <code>msno.bar()</code> function, to visualize missingness across the different variables in our <code>DataFrame</code>:</p>
<div id="cell-29" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:32.895365Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:32.894153Z&quot;}" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> missingno <span class="im">as</span> msno</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-30" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:33.719853Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:33.065689Z&quot;}" data-outputid="04709186-00b2-4984-ef7f-ea9e4c767d9d" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>msno.bar(strike_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Although we see in hindsight that the visual properties of this plot would not have been that useful in discovering the missing values in <code>TGTCOUNTRY</code> (I say “visual properties” because it still helpfully provides the non-missing <strong>counts</strong> at the top of each bar, which could have allowed us to see this issue), the plot is <strong>very useful</strong> for discovering the missingness prevalent in the <code>TGTTYPE</code> variable. So, just like in the case of <code>TGTCOUNTRY</code>, we will move on while <strong>keeping in mind that this variable has an even more extreme issue with missingness</strong> that will bias our results (until we learn how to explicitly incorporate and de-bias the missingness!)</p>
</section>
<section id="different-formats-within-the-same-column" class="level2">
<h2 class="anchored" data-anchor-id="different-formats-within-the-same-column">(4) Different Formats Within The Same Column</h2>
<section id="the-ambiguous-object-type" class="level3">
<h3 class="anchored" data-anchor-id="the-ambiguous-object-type">(4.1) The Ambiguous <code>object</code> Type</h3>
<p>As our next EDA task, let’s look into that <strong>(!)</strong> in the table above: while the rest of the variables are in fairly unambiguous formats, <code>object</code> is a particularly scary datatype in Pandas, since “object” in fact just means that <strong>the datatype of a given value in this column could be anything</strong>. If you know Java, for example, you know that <code>Object</code> is the datatype that all other datatypes are <strong>subtypes</strong> of. Similarly, in Python, every class implicitly <strong>inherits</strong> the properties of <a href="https://docs.python.org/3/library/functions.html#object" target="_blank">the <code>object</code> class</a>.</p>
<p>Looking at the output of <code>head()</code> from above, however, you may reasonably think that the entries in this column will all be of <code>string</code> type. And this instinct would be further enforced by <strong>checking the datatypes</strong> of the first five entries in the column:</p>
<div id="cell-35" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:35.421402Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:35.399600Z&quot;}" data-outputid="6307b633-cb15-467d-d264-bb58e014c697" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE'</span>].head().<span class="bu">apply</span>(<span class="bu">type</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>0    &lt;class 'str'&gt;
1    &lt;class 'str'&gt;
2    &lt;class 'str'&gt;
3    &lt;class 'str'&gt;
4    &lt;class 'str'&gt;
Name: MSNDATE, dtype: object</code></pre>
</div>
</div>
<p>Therefore, you might start moving ahead, working with this column as if it is a string column. <strong>You should push back on this instinct!!</strong> It will save you so many headaches later on, when you are neck-deep in the data analysis, if you <strong>verify what’s going on with any columns that Pandas loaded as <code>object</code> type</strong> right at the beginning!</p>
<p>For example, rather than drawing inferences about the <strong>entire dataset</strong> from only the <strong>first five columns</strong> (a procedure jokingly referred to as <a href="https://geoffreywu.me/blog/engineers-induction/" target="_blank">“engineer’s induction”</a>), we can do something a bit less error-prone by making a <strong>new column</strong> <code>MSNDATE_type</code> which just tells us the type of each value in the <code>MSNDATE</code> column, then checking whether or not every entry in <code>MSNDATE_type</code> is <code>string</code>. If it is, then we’re fine adopting the it’s-a-string-variable assumption and moving on. But if it’s not, we’ll have to do something to handle the mismatch. Let’s see what happens. We’ll make the column, then we’ll use the <code>value_counts()</code> function from Pandas to see the distribution of datatypes in the column (where now we remember that we pretty much always want to include the <code>dropna = False</code> parameter):</p>
<div id="cell-37" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:36.519787Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:36.488456Z&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_type'</span>] <span class="op">=</span> strike_df[<span class="st">'MSNDATE'</span>].<span class="bu">apply</span>(<span class="bu">type</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-38" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:36.701663Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:36.697681Z&quot;}" data-outputid="9d328c7a-fae3-4cd3-901d-ccd1485e2359" data-execution_count="15">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_type'</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>MSNDATE_type
&lt;class 'str'&gt;    1007674
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>So far so good: Pandas loaded the column as type <code>object</code>, which <strong>often means</strong> but <strong>does not always mean</strong> that the column is filled with <code>string</code> variables. There is still one more issue with this column, however, looming on the horizon…</p>
</section>
<section id="splitting-the-column-into-parts" class="level3">
<h3 class="anchored" data-anchor-id="splitting-the-column-into-parts">(4.2) Splitting The Column Into Parts</h3>
<p>Since in general we want to analyze the <strong>yearly volume</strong> of strikes in each country, the format of the values in the <code>MSNDATE</code> column is not that helpful to us at the moment. So, again we might proceed by intuition, using <strong>engineer’s induction</strong> on the first five rows of the <code>DataFrame</code> to infer that we can just <strong>split on the <code>-</code> character</strong> to quickly divide this single column into three separate columns: one for year, one for month, and one for day.</p>
<p>Let’s see what happens when we try this out.</p>
<p><strong>Writing the Parse Function</strong></p>
<p>In Python, unlike the nice <code>separate_wider_*()</code> functions in R that I talked about in <a href="https://jjacobs.me/dsan5000/463a01339cf0f456ba54a1849df50d1a22c247e3/writeups/tidyverse-split-column/" target="_blank">this writeup</a>, I personally haven’t found all that many helpful functions specially-made for splitting a string up into pieces.</p>
<p>So, what I <strong>usually</strong> do in this type of situation (but see a few sections below) is utilize the following setup: as a nice “trick” for generating multiple columns from one individual column, Pandas allows you to write functions which return <code>pd.Series</code> objects (these <code>Series</code> objects are sort of like one-dimensional <code>DataFrame</code>s), and then use this function to set the values of <strong>multiple columns</strong> in one “sweep” using syntax like:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> function_returning_series_object(value):</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">"""</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">  A function that will take in a single value from a column and</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">  return a pd.Series object, where the **keys** in the pd.Series</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">  correspond to the **names of the columns** you're hoping to create</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">  """</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="op">//</span> Do something <span class="cf">with</span> `value` to generate these results</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  resulting_x_value <span class="op">=</span> <span class="st">'first result'</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  resulting_y_value <span class="op">=</span> <span class="st">'second result'</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  resulting_z_value <span class="op">=</span> <span class="st">'third result'</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  series_values <span class="op">=</span> {</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'x'</span> <span class="op">=</span> resulting_x_value,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'y'</span> <span class="op">=</span> resulting_y_value,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'z'</span> <span class="op">=</span> resulting_z_value</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> pd.Series(series_values)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="op">//</span> Specify the names of the columns you<span class="st">'re about to create</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="er">columns_to_create = </span>[<span class="st">'x'</span>,<span class="st">'y'</span>,<span class="st">'z'</span>]</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="op">//</span> And use the <span class="bu">apply</span>() function to <span class="st">"send"</span> the values of some existing column</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="op">//</span> to the function_returning_series_object() function defined above</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>df[columns_to_create] <span class="op">=</span> df[<span class="st">'some_existing_column'</span>].<span class="bu">apply</span>(function_returning_series_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In our case, so you can see this in action, let’s define a function that will take in the values of the <code>MSNDATE</code> column (which we expect to have the format <code>YY-MM-DD</code>, split these values on the <code>-</code> character, and return the three resulting pieces in <code>pd.Series</code> form with the keys <code>year</code>, <code>month</code>, and <code>day</code>.</p>
<div id="cell-44" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:37.911063Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:37.892067Z&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> split_date(date_val):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  date_elts <span class="op">=</span> date_val.split(<span class="st">"-"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  date_values <span class="op">=</span> {</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>      <span class="st">'year'</span>: date_elts[<span class="dv">0</span>],</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">'month'</span>: date_elts[<span class="dv">1</span>],</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">'day'</span>: date_elts[<span class="dv">2</span>]</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> pd.Series(date_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="The `tqdm` Library">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The <code>tqdm</code> Library
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Quick Note: <code>tqdm</code></strong></p>
<p>When we use the <code>apply()</code> function from Pandas to apply our <code>split_date()</code> function to each value of the <code>MSNDATE</code> column, it will take kind of a long time to iterate through and parse each date. For this reason, I’m including example code here showing how to import and use the third-party Python library <code>tqdm</code> to create a new <code>progress_apply()</code> function. If the waiting feels tedious on your machine, for example, you can call <code>progress_apply()</code> in the place of <code>apply()</code>, which will display a <strong>progress bar</strong> showing far along it is. In Colab this will work right away, since <code>tqdm</code> comes pre-installed. Depending on your environment it may crash though, since some versions of <code>tqdm</code> are incompatible with some versions of <code>pandas</code>, so to be safe I’m sticking with the regular <code>.apply()</code> function</p>
</div>
</div>
<div id="cell-46" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:38.315327Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:38.288744Z&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm.notebook <span class="im">import</span> tqdm</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>tqdm.pandas()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Back to EDA</strong></p>
<p>The running time of the <code>progress_apply()</code> call will be bad enough, but as we’ll see, it gets even worse: right near the end, about 63% of the way through, the code will <strong>crash</strong> with an error! (You can uncomment the following code, run it, and wait a bit to see the error if you’d like, or just jump past the following cell)</p>
<div id="cell-48" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:39.221503Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:39.191943Z&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">## And apply it to MSNDATE</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#columns_to_create = ['year','month','day']</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#strike_df[columns_to_create] = strike_df['MSNDATE'].progress_apply(split_date)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The error looks like:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="op">&lt;</span>ipython<span class="op">-</span><span class="bu">input</span><span class="op">-</span><span class="dv">35</span><span class="op">-</span>ec79f5e7def4<span class="op">&gt;</span> <span class="kw">in</span> split_date(date_val)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>      <span class="dv">3</span>   date_values <span class="op">=</span> {</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>      <span class="dv">4</span>       <span class="st">'year'</span>: date_elts[<span class="dv">0</span>],</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="op">----&gt;</span> <span class="dv">5</span>       <span class="st">'month'</span>: date_elts[<span class="dv">1</span>],</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>      <span class="dv">6</span>       <span class="st">'day'</span>: date_elts[<span class="dv">2</span>]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>      <span class="dv">7</span>   }</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="pp">IndexError</span>: <span class="bu">list</span> index out of <span class="bu">range</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>So what happened?</p>
<p>Long story short, <strong>engineer’s induction failed us again</strong>. It turns out that some entries within the <code>MSNDATE</code> column contain dates in a <strong>different format</strong> from the format we saw in the first 5 rows of the dataset. But how did I magically figure this out?</p>
<p>Let’s start by carrying out Engineer’s Induction 2.0 (TM), by looking at the <strong>tail</strong> of <code>strike_df</code> rather than the head. Sometimes, if the column has one format at the beginning, but another near the end, this will show us the alternative format:</p>
<div id="cell-50" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:40.302946Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:40.279992Z&quot;}" data-outputid="a422f9e7-919d-4eb2-d6f0-6f8b913a62f3" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>strike_df.tail()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MFUNC_DESC</th>
<th data-quarto-table-cell-role="th">MISSIONID</th>
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">THOR_DATA_VIET_ID</th>
<th data-quarto-table-cell-role="th">MSNDATE</th>
<th data-quarto-table-cell-role="th">SOURCEID</th>
<th data-quarto-table-cell-role="th">NUMWEAPONSDELIVERED</th>
<th data-quarto-table-cell-role="th">TGTTYPE</th>
<th data-quarto-table-cell-role="th">TGTLATDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">TGTLONDDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">MSNDATE_type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1007669</td>
<td>STRIKE</td>
<td>1405</td>
<td>LAOS</td>
<td>4559448</td>
<td>1973-01-01</td>
<td>58102</td>
<td>0</td>
<td>PERSONNEL\ANY</td>
<td>15.191111</td>
<td>106.206666</td>
<td>&lt;class 'str'&gt;</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1007670</td>
<td>STRIKE</td>
<td>8719</td>
<td>LAOS</td>
<td>4560531</td>
<td>1972-05-08</td>
<td>68563</td>
<td>0</td>
<td>NaN</td>
<td>16.758055</td>
<td>106.461944</td>
<td>&lt;class 'str'&gt;</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1007671</td>
<td>STRIKE</td>
<td>9526</td>
<td>SOUTH VIETNAM</td>
<td>4561255</td>
<td>1972-07-10</td>
<td>69287</td>
<td>0</td>
<td>NaN</td>
<td>16.684166</td>
<td>107.053888</td>
<td>&lt;class 'str'&gt;</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1007672</td>
<td>STRIKE</td>
<td>0692</td>
<td>LAOS</td>
<td>4650354</td>
<td>1970-11-28</td>
<td>527864</td>
<td>0</td>
<td>TRUCKS</td>
<td>17.286388</td>
<td>105.609722</td>
<td>&lt;class 'str'&gt;</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1007673</td>
<td>STRIKE</td>
<td>7232</td>
<td>LAOS</td>
<td>4651825</td>
<td>1971-10-19</td>
<td>541658</td>
<td>4</td>
<td>NaN</td>
<td>15.292777</td>
<td>107.137500</td>
<td>&lt;class 'str'&gt;</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>We’re not so lucky this time. The <strong>last 5 values</strong> of the <code>MSNDATE</code> column look like they’re formatted the same way as the first 5 values are.</p>
<p>So, next let’s do something a bit smarter, and just check <strong>how many <code>-</code> characters</strong> each entry has—we can code this check in a very similar way to how we coded the check above when we looked at the <code>type</code> of each entry in the column.</p>
<p>In fact, here we don’t even need to come up with our own function and use <code>apply()</code> or anything like that, since Pandas has built-in functionality allowing us to access (by using the <code>.str</code> suffix after extracting just the <code>string</code>-format column) any of Python’s built-in functions for <code>string</code>s, like <code>len()</code> or <code>replace()</code>, at which point Pandas will then automatically apply our chosen to each value in the column.</p>
<p>So, let’s use this <code>.str</code> suffix to apply the built-in <code>count()</code> function (that Python provides for all <code>string</code> objects) to each value of <code>MSNDATE</code>, counting the number of times that <code>-</code> appears in each value, then look at the <strong>distribution</strong> of these counts across the entire column:</p>
<div id="cell-52" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:41.167625Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:40.983487Z&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_dashcount'</span>] <span class="op">=</span> strike_df[<span class="st">'MSNDATE'</span>].<span class="bu">str</span>.count(<span class="st">"-"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-53" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:41.518252Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:41.499410Z&quot;}" data-outputid="0db153df-876c-43be-8d7e-ba5a39511e1f" data-execution_count="21">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_dashcount'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>MSNDATE_dashcount
2    993524
0     14150
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>And we’ve found our issue: 14,150 of the rows do <strong>not</strong> use a <code>YYYY-MM-DD</code> format! Since we now have this <code>MSNDATE_dashcount</code> column available to use, let’s filter the full <code>DataFrame</code> to look at just (the first few) rows where it is equal to <code>0</code>, i.e., rows where the <code>MSNDATE</code> column does <strong>not</strong> contain any dashes:</p>
<div id="cell-55" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:42.317175Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:42.304287Z&quot;}" data-outputid="d204aca4-2e2d-4d5b-97bf-4c634670abc4" data-execution_count="22">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>strike_df.loc[strike_df[<span class="st">'MSNDATE_dashcount'</span>] <span class="op">==</span> <span class="dv">0</span>,].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MFUNC_DESC</th>
<th data-quarto-table-cell-role="th">MISSIONID</th>
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">THOR_DATA_VIET_ID</th>
<th data-quarto-table-cell-role="th">MSNDATE</th>
<th data-quarto-table-cell-role="th">SOURCEID</th>
<th data-quarto-table-cell-role="th">NUMWEAPONSDELIVERED</th>
<th data-quarto-table-cell-role="th">TGTTYPE</th>
<th data-quarto-table-cell-role="th">TGTLATDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">TGTLONDDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">MSNDATE_type</th>
<th data-quarto-table-cell-role="th">MSNDATE_dashcount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">639026</td>
<td>STRIKE</td>
<td>JH301</td>
<td>SOUTH VIETNAM</td>
<td>2876015</td>
<td>19700409</td>
<td>258195</td>
<td>12</td>
<td>AREA\DEPOT</td>
<td>14.825953</td>
<td>107.716270</td>
<td>&lt;class 'str'&gt;</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">639027</td>
<td>STRIKE</td>
<td>JH309</td>
<td>SOUTH VIETNAM</td>
<td>2876638</td>
<td>19700216</td>
<td>262548</td>
<td>24</td>
<td>AREA\DEPOT</td>
<td>14.510215</td>
<td>108.768815</td>
<td>&lt;class 'str'&gt;</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">639028</td>
<td>STRIKE</td>
<td>01305</td>
<td>SOUTH VIETNAM</td>
<td>2876852</td>
<td>19651029</td>
<td>221263</td>
<td>0</td>
<td>UNKNOWN\UNIDENTIFIED</td>
<td>10.186505</td>
<td>106.229604</td>
<td>&lt;class 'str'&gt;</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">639029</td>
<td>STRIKE</td>
<td>JG402</td>
<td>SOUTH VIETNAM</td>
<td>2877103</td>
<td>19701114</td>
<td>219532</td>
<td>24</td>
<td>AREA\DEPOT</td>
<td>16.331801</td>
<td>107.012509</td>
<td>&lt;class 'str'&gt;</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">639030</td>
<td>STRIKE</td>
<td>J8012</td>
<td>LAOS</td>
<td>2877181</td>
<td>19700721</td>
<td>219801</td>
<td>48</td>
<td>TRUCK PARK\STOP</td>
<td>16.286964</td>
<td>106.922250</td>
<td>&lt;class 'str'&gt;</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>And we see that, to our relief, the issue isn’t so bad: if engineer’s induction <strong>does</strong> hold for this situation, then (hopefully) we can split those 14,150 rows <strong>without</strong> any dashes by just taking the <code>MSNDATE</code> values in these rows and directly extracting the first 4 characters as the <code>year</code>, the next 2 characters as the <code>month</code> and the final 2 characters as the <code>day</code>. As an additional sanity check here, since we are using engineer’s induction, we can check the full range of possible <strong>lengths</strong> of the <code>MSNDATE</code> values:</p>
<div id="cell-57" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:43.064721Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:42.964374Z&quot;}" data-outputid="74920a36-b450-4b00-cc3c-f593ef2aedfd" data-execution_count="23">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_len'</span>] <span class="op">=</span> strike_df[<span class="st">'MSNDATE'</span>].<span class="bu">str</span>.<span class="bu">len</span>()</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'MSNDATE_len'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>MSNDATE_len
10    993524
8      14150
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>And we see another encouraging sign: that there is not (for example) some third length that the values of this column can have, that we’d need to worry about on top of the two different formats we’ve found</p>
<p><em>(There still <strong>could</strong> be more than two formats, if the additional formats happened to produce date strings with length 8 or 10, but we’ll worry about that if we experience more issues with splitting <code>MSNDATE</code> under the assumption of two formats)</em></p>
<p><strong>Re-Coding the Date Parsing Function: v2.1</strong></p>
<p>So let’s make an updated version of our <code>split_date()</code> function, which explicitly checks whether the date it is given is encoded in the 8-character or 10-character format, and does the splitting accordingly:</p>
<div id="cell-60" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:43.883980Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:43.849627Z&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> split_date_v2_1(date_val):</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> <span class="bu">len</span>(date_val) <span class="op">==</span> <span class="dv">10</span>:</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Do what we did before, using .split()</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    date_elts <span class="op">=</span> date_val.split(<span class="st">"-"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    date_values <span class="op">=</span> {</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">'year'</span>: date_elts[<span class="dv">0</span>],</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>      <span class="st">'month'</span>: date_elts[<span class="dv">1</span>],</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">'day'</span>: date_elts[<span class="dv">2</span>]</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Assume it is in YYYYMMDD format, so that we can</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># just extract substrings to obtain Y, M, and D</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>    date_values <span class="op">=</span> {</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'year'</span>: date_val[<span class="dv">0</span>:<span class="dv">4</span>],</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'month'</span>: date_val[<span class="dv">4</span>:<span class="dv">6</span>],</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'day'</span>: date_val[<span class="dv">6</span>:<span class="dv">8</span>]</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> pd.Series(date_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now we <strong>could</strong> run this using the same <code>.apply()</code> code as before, to see if it successfully parses the column. In the first version of the writeup I did run it, but it took about ~5 minutes, which is too long for a reasonable quick-learning writeup, imo! (You could just go ahead and create a cell containing the following code, and run it, if you are ok waiting for 5mins:)</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>columns_to_create <span class="op">=</span> [<span class="st">'year'</span>,<span class="st">'month'</span>,<span class="st">'day'</span>]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>strike_df[columns_to_create] <span class="op">=</span> strike_df[<span class="st">'MSNDATE'</span>].progress_apply(split_date_v2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>For me, though, 5 minutes is too slow, so here is a screenshot of the output after this call to <code>progress_apply()</code> has finished:</p>
<p><img src="images/pandas_progress.jpg" class="img-fluid"></p>
<div class="callout callout-style-default callout-note callout-titled" title="The `swifter` Library">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The <code>swifter</code> Library
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Another Quick Note: <code>swifter</code></strong></p>
<p><em>Like last time, this may take a while to complete: cases like these are where I highly recommend using <code>tqdm</code>, at a minimum!</em></p>
<p><em>There is also the third-party library <a href="https://github.com/jmcarpenter2/swifter" target="_blank"><code>swifter</code></a>, which would be nice for the kinds of <a href="https://en.wikipedia.org/wiki/Embarrassingly_parallel" target="_blank">embarrasingly parallel</a> tasks we’re applying to the column here, except that (as far as I can tell) <code>swifter</code> is only able to provide speedups for <strong>numeric</strong> operations :/ I thought I’d mention it here, however, since if you are doing some <strong>numeric</strong> operation that’s taking this long, you might try seeing if <code>swifter</code> will speed up your code!</em></p>
</div>
</div>
<p>And as an example of the vast differences that can arise between efficient and inefficient versions of processing code, even in EDA: since I really only need to extract the <strong>year</strong> (rather than the three elements of each date) for the remaining analysis, for speed I used the following <code>lambda</code> function instead, which just scoops out the <strong>first 4 characters</strong> of the <code>MSNDATE</code> value (which works because, in either format, the first 4 characters of the string contain the year), and it took approximately 1 second to finish:</p>
<div id="cell-64" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Depending on your Jupyter environment, you may need to install/update the</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># `ipywidgets` library for `tqdm` to work correctly</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#!pip install ipywidgets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-65" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:46.115212Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:45.710618Z&quot;}" data-outputid="2e229c70-7044-4666-d18e-b5ba1c482dba" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># progress_apply() version (with progress bar)</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#strike_df['year'] = strike_df['MSNDATE'].progress_apply(lambda x: x[0:4])</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># apply() version</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'year'</span>] <span class="op">=</span> strike_df[<span class="st">'MSNDATE'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x[<span class="dv">0</span>:<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, now that we’ve extracted just the <strong>year</strong> of the mission into its own column, let’s convert that column from <code>string</code> format into <code>int</code> format. There are a lot of ways to do this type of conversion, but for me the <code>pd.to_numeric()</code> function is most useful for several reasons, so I’ll use that:</p>
<div id="cell-67" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:46.568043Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:46.561428Z&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'year'</span>] <span class="op">=</span> pd.to_numeric(strike_df[<span class="st">'year'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And as we can see by checking the <code>.dtypes</code> attribute (as with <strong>shape</strong>, remember that <strong>dtypes</strong> is <strong>not a function</strong>!), <code>year</code> now has the <code>int64</code> (64-bit integer) format, as we wanted:</p>
<div id="cell-69" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:47.261326Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:47.234165Z&quot;}" data-outputid="788a8e1e-9fbf-4d1c-c31a-c55bba4d3c9f" data-execution_count="28">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>strike_df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>MFUNC_DESC              object
MISSIONID               object
TGTCOUNTRY              object
THOR_DATA_VIET_ID        int64
MSNDATE                 object
SOURCEID                 int64
NUMWEAPONSDELIVERED      int64
TGTTYPE                 object
TGTLATDD_DDD_WGS84     float64
TGTLONDDD_DDD_WGS84    float64
MSNDATE_type            object
MSNDATE_dashcount        int64
MSNDATE_len              int64
year                     int64
dtype: object</code></pre>
</div>
</div>
</section>
</section>
<section id="collapsing-messy-categorical-variables-into-clean-ones" class="level2">
<h2 class="anchored" data-anchor-id="collapsing-messy-categorical-variables-into-clean-ones">(5) Collapsing Messy Categorical Variables Into Clean Ones</h2>
<p>The one variable we should still look at is <code>TGTTYPE</code>: although we already saw how messy it was in the sense of having lots of missing values, it turns out that it is also messy in the sense of having lots and lots of potential values, some of which are very similar but not identical, so that (for example) trying to include this variable as a “factor variable” in a cross-tabulation or a two-way plot (see below) would result in a very messy plot with too many bars/lines/colors/etc.</p>
<p>This becomes clear if we run the following code, showing that there are <strong>235 possible values</strong> that this categorical variable can take on:</p>
<div id="cell-72" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:48.475306Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:48.472151Z&quot;}" data-outputid="a5796e7e-0fce-4f6c-be18-876a1367479a" data-execution_count="29">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'TGTTYPE'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>TGTTYPE
AREA\DEPOT         118271
MOTOR VEHICLE      108533
TRUCK PARK\STOP     77840
ROAD                60494
ANTI-AIRCRAFT       52870
                    ...  
AMMO BLDG               1
CP                      1
MOUNTAIN PASS           1
SAM OXIDIZER            1
MIG19                   1
Name: count, Length: 235, dtype: int64</code></pre>
</div>
</div>
<p>Since we’re focusing on EDA and visualization, though, let’s treat this <code>value_counts()</code> table as a “mini-dataset” and generate an EDA-style visualization of how many instances of each possible category actually appear in the broader dataset. We’ll call this mini-dataset <code>target_dist</code>, since it represents just the counts (and therefore, as a whole, the distribution) of the various possible target-type categories. Note, however, that because <code>value_counts()</code> returns a <strong><code>pd.Series</code></strong> object, <strong>not</strong> a <code>pd.DataFrame</code> object, we’ll need to explicitly convert its return value into a <code>pd.DataFrame</code> (plus turn the index column into a “regular” column and rename it from <code>index</code> into something more informative) in order to use it with Seaborn.</p>
<div id="cell-74" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:49.337330Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:49.332606Z&quot;}" data-outputid="20ad9ba6-c3df-428c-a2e8-c242e8eb7cc5" data-execution_count="30">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>target_dist_df <span class="op">=</span> pd.DataFrame(strike_df[<span class="st">'TGTTYPE'</span>].value_counts()).reset_index()</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>target_dist_df.columns <span class="op">=</span> [<span class="st">'TGTTYPE_val'</span>,<span class="st">'count'</span>]</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>target_dist_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TGTTYPE_val</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>AREA\DEPOT</td>
<td>118271</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>MOTOR VEHICLE</td>
<td>108533</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>TRUCK PARK\STOP</td>
<td>77840</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>ROAD</td>
<td>60494</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ANTI-AIRCRAFT</td>
<td>52870</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">230</td>
<td>AMMO BLDG</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">231</td>
<td>CP</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">232</td>
<td>MOUNTAIN PASS</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">233</td>
<td>SAM OXIDIZER</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">234</td>
<td>MIG19</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>235 rows × 2 columns</p>
</div>
</div>
</div>
</div>
<div id="cell-75" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:49.627851Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:49.606014Z&quot;}" data-outputid="5852a2c0-b7c4-4826-c248-e386f81e9c9d" data-execution_count="31">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>target_dist_df.iloc[:<span class="dv">20</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TGTTYPE_val</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>AREA\DEPOT</td>
<td>118271</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>MOTOR VEHICLE</td>
<td>108533</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>TRUCK PARK\STOP</td>
<td>77840</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>ROAD</td>
<td>60494</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>ANTI-AIRCRAFT</td>
<td>52870</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>TROOPS</td>
<td>47532</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>BRIDGE</td>
<td>28272</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>UNKNOWN\UNIDENTIFIED</td>
<td>27328</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>BUILDINGS</td>
<td>24453</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>SEGMENT\TRANS ROUTE</td>
<td>24181</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>FORD</td>
<td>13893</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>WATER VEHICLES</td>
<td>10845</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>TRUCKS</td>
<td>10224</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>INTERDICTION POINT</td>
<td>9414</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>FERRY</td>
<td>9121</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>BIVOUAC</td>
<td>8505</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>ROADS\HIGHWAYS</td>
<td>7762</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>STORAGE AREA</td>
<td>7762</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>CAVE</td>
<td>6350</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>PERSONNEL\ANY</td>
<td>6314</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Now we can think about how to visualize this: since <code>target_dist</code> represents a <strong>distribution</strong> (in particular, a <strong>distribution of counts</strong>), essentially we have already done the set of computations that the <code>sns.displot()</code> function demonstrated in the very beginning of the <a href="https://jfh.georgetown.domains/dsan5000/slides-and-labs/_site/content/slides/seaborn-introduction/notes.html" target="_blank">W06 Lab Demo</a> performs under the hood. Meaning: if we <strong>hadn’t</strong> already computed counts for each value of <code>TGTTYPE</code>, we could use <code>sns.displot()</code> with the original <code>strike_df</code> dataset to visualize these counts. Since we’ve already computed counts, however, we can more straightforwardly just plot each count as a bar in a <code>sns.barplot()</code> visualization (which will look identical to what <code>sns.displot()</code> would generate given <code>strike_df</code>).</p>
<p><em>(I mentioned the fact that <code>target_dist</code> is a distribution of counts since, although <code>displot()</code> can be used for both <strong>probability</strong> distributions and distributions of <strong>counts</strong>, the y-axis for plots of <strong>counts</strong> will be even easier to interpret than the y-axis for plots of probability mass values, since in the latter case the y-axis values will be “squished down” into decimals ranging from 0 to 1)</em></p>
<div id="cell-77" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:51.045224Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:50.678838Z&quot;}" data-outputid="59d46a26-3773-4a05-bc10-be69a43e9af7" data-execution_count="33">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Since Seaborn is built on top of `matplotlib`, we usually import these two libraries</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in the following order, and use the aliases `plt` and `sns`, respectively"</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>target_dist_df,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"TGTTYPE_val"</span>,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'count'</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>).<span class="bu">set</span>(xticks<span class="op">=</span>[], xticklabels<span class="op">=</span>[])</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-33-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>After the call to <code>sns.barplot()</code> in the previous cell, notice that I’m also calling <code>.set()</code> with the options <code>xticks=[]</code> and <code>xticklabels=[]</code>. This call with these options simply removes all ticks and tick labels on the x-axis of the plot, since otherwise it would have displayed a chaotic overlapping mass of 235 ticks and 235 labels. Without these ticks/labels, we are able to focus just on the distribution of the y-axis values, and especially the fact that they start to <strong>decrease rapidly after a certain point</strong>.</p>
<p>This rapid decrease tells us, for example, that we can probably either</p>
<ul>
<li><ol type="a">
<li>aggregate the rarely-appearing values into broader categories, to see if they are (for example) just slightly-modified versions of the more-frequently-appearing values [the safer, more statistically-principled approach], or</li>
</ol></li>
<li><ol start="2" type="a">
<li>ignore these values when we’re examining cross-tabulations and/or generating visualizations where data is grouped by these values.</li>
</ol></li>
</ul>
<p>Since we’re focusing on EDA, I’ll be employing approach (b), but please keep in mind that <strong>you might be throwing away important information</strong> by ignoring these less-frequently-occurring values (many examples come to mind, but to avoid making the writeup any longer I will just say, feel free to ask about these cases!)</p>
<p>Therefore, I’m going to (arbitrarily!) <strong>keep the top 10 most-frequently occurring values</strong>, and then collapse any values beyond this top 10 down into an 11th catch-all category called <strong>“other”</strong>:</p>
<div id="cell-79" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:52.137495Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:52.110814Z&quot;}" data-outputid="fa4766ef-89b9-49da-8594-9a343bdf50d3" data-execution_count="37">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract just the 10 most-frequently occurring values</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>rank_cutoff <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>most_frequent_values <span class="op">=</span> target_dist_df[<span class="st">'TGTTYPE_val'</span>].iloc[:rank_cutoff].values</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print them out (for future reference)</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(most_frequent_values)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Then take the **set difference** between the **full set of values** and the</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># **values that we're keeping**, and re-map these remaining values onto the single value</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># "other"</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>all_values <span class="op">=</span> target_dist_df[<span class="st">'TGTTYPE_val'</span>].values</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>non_frequent_values <span class="op">=</span> [v <span class="cf">for</span> v <span class="kw">in</span> all_values <span class="cf">if</span> v <span class="kw">not</span> <span class="kw">in</span> most_frequent_values]</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity check</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>num_non_frequent <span class="op">=</span> <span class="bu">len</span>(non_frequent_values)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>num_non_frequent<span class="sc">}</span><span class="ss"> non-frequent values"</span>)</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="co"># And apply the mapping to the original strike_df dataset</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>rename_map <span class="op">=</span> {nfv: <span class="st">"other"</span> <span class="cf">for</span> nfv <span class="kw">in</span> non_frequent_values}</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'TGTTYPE'</span>] <span class="op">=</span> strike_df[<span class="st">'TGTTYPE'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: rename_map[x] <span class="cf">if</span> x <span class="kw">in</span> rename_map <span class="cf">else</span> x)</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print out the new value_counts, to check that the mapping worked</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'TGTTYPE'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['AREA\\DEPOT' 'MOTOR VEHICLE' 'TRUCK PARK\\STOP' 'ROAD' 'ANTI-AIRCRAFT'
 'TROOPS' 'BRIDGE' 'UNKNOWN\\UNIDENTIFIED' 'BUILDINGS'
 'SEGMENT\\TRANS ROUTE']
225 non-frequent values</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>TGTTYPE
other                   161206
AREA\DEPOT              118271
MOTOR VEHICLE           108533
TRUCK PARK\STOP          77840
ROAD                     60494
ANTI-AIRCRAFT            52870
TROOPS                   47532
BRIDGE                   28272
UNKNOWN\UNIDENTIFIED     27328
BUILDINGS                24453
SEGMENT\TRANS ROUTE      24181
Name: count, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="tabulation-and-cross-tabulation" class="level2">
<h2 class="anchored" data-anchor-id="tabulation-and-cross-tabulation">(6) Tabulation and Cross-Tabulation</h2>
<p>Now that we’re finally done with those fairly messy/tedious cleaning steps, let’s make some tables!</p>
<section id="summary-statistics-table-.describe" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-table-.describe">(6.1) Summary Statistics Table: <code>.describe()</code></h3>
<p>First, as in the other lab demo you have, let’s use <code>.describe()</code> to create a table showing us some basic summary statistics about our now-cleaned variables. Your first instinct might be to just call <code>strike_df.describe()</code>, as in the following code cell, but that’s another instinct you should probably push back on:</p>
<div id="cell-84" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:55.040450Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:54.864702Z&quot;}" data-outputid="d4cf3d94-f909-4cee-8737-c57ff0678758" data-execution_count="38">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>strike_df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">THOR_DATA_VIET_ID</th>
<th data-quarto-table-cell-role="th">SOURCEID</th>
<th data-quarto-table-cell-role="th">NUMWEAPONSDELIVERED</th>
<th data-quarto-table-cell-role="th">TGTLATDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">TGTLONDDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">MSNDATE_dashcount</th>
<th data-quarto-table-cell-role="th">MSNDATE_len</th>
<th data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>1.007674e+06</td>
<td>1.007674e+06</td>
<td>1.007674e+06</td>
<td>969931.000000</td>
<td>969931.000000</td>
<td>1.007674e+06</td>
<td>1.007674e+06</td>
<td>1.007674e+06</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>2.264882e+06</td>
<td>1.712625e+06</td>
<td>1.202383e+01</td>
<td>17.221362</td>
<td>105.875013</td>
<td>1.971916e+00</td>
<td>9.971916e+00</td>
<td>1.969216e+03</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>1.278396e+06</td>
<td>1.321200e+06</td>
<td>5.958607e+01</td>
<td>1.801880</td>
<td>1.249900</td>
<td>2.353301e-01</td>
<td>2.353301e-01</td>
<td>1.738883e+00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>4.000000e+00</td>
<td>3.000000e+00</td>
<td>0.000000e+00</td>
<td>0.247721</td>
<td>43.416666</td>
<td>0.000000e+00</td>
<td>8.000000e+00</td>
<td>1.965000e+03</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1.164722e+06</td>
<td>5.796808e+05</td>
<td>0.000000e+00</td>
<td>16.430555</td>
<td>105.712000</td>
<td>2.000000e+00</td>
<td>1.000000e+01</td>
<td>1.968000e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>2.264671e+06</td>
<td>1.454324e+06</td>
<td>4.000000e+00</td>
<td>17.125000</td>
<td>106.155833</td>
<td>2.000000e+00</td>
<td>1.000000e+01</td>
<td>1.969000e+03</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>3.218455e+06</td>
<td>2.593384e+06</td>
<td>1.200000e+01</td>
<td>18.000000</td>
<td>106.638000</td>
<td>2.000000e+00</td>
<td>1.000000e+01</td>
<td>1.970000e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>4.670411e+06</td>
<td>4.909001e+06</td>
<td>9.822000e+03</td>
<td>135.717675</td>
<td>167.500000</td>
<td>2.000000e+00</td>
<td>1.000000e+01</td>
<td>1.975000e+03</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>We see that this output looks kind of messy, if we don’t <strong>filter out non-numeric-variable columns</strong> like the <code>id</code> variables or the <code>_dashcount</code> and <code>_len</code> variables we created as helper columns above. If we <strong>do</strong> take care to filter out those columns first, <code>.describe()</code> provides us with more focused and more useful information.</p>
<p>First we drop the helper columns, since we don’t need these anymore now that <code>MSNDATE</code> has been cleaned to our satisfaction. We use the <code>inplace = True</code> argument to Pandas’ <code>drop()</code> function to indicate that we want to <strong>permanently</strong> drop these two columns:</p>
<div id="cell-86" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:56.167531Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:56.122234Z&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>cols_to_drop <span class="op">=</span> [</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MSNDATE_len'</span>,</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MSNDATE_dashcount'</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MSNDATE_type'</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>strike_df.drop(columns <span class="op">=</span> cols_to_drop, inplace <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now we specify just the subset of numeric columns we’d like summaries of, and call <code>.describe()</code> only on that subset:</p>
<div id="cell-88" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:56.921797Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:56.802360Z&quot;}" data-outputid="a758c776-b4f7-4b61-c4a4-5d03ca327581" data-execution_count="40">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I break the column names onto separate lines here to make it easy for</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># myself to go back and include/exclude columns from the call to describe():</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># I just comment/uncomment the line corresponding to the column I want to</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># hide/show, respectively</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="op">=</span> [</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NUMWEAPONSDELIVERED'</span>,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTLATDD_DDD_WGS84'</span>,</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTLONDDD_DDD_WGS84'</span>,</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'year'</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.option_context() has kind of a strange syntax, but it just allows us to</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="co"># specify how to format each number in the result of the call to describe()</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="co"># without having to worry about permanently changing our Pandas display</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a><span class="co"># settings</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pd.option_context(<span class="st">'display.float_format'</span>, <span class="st">'</span><span class="sc">{:.2f}</span><span class="st">'</span>.<span class="bu">format</span>):</span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  display(strike_df[numeric_cols].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">NUMWEAPONSDELIVERED</th>
<th data-quarto-table-cell-role="th">TGTLATDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">TGTLONDDD_DDD_WGS84</th>
<th data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>1007674.00</td>
<td>969931.00</td>
<td>969931.00</td>
<td>1007674.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>12.02</td>
<td>17.22</td>
<td>105.88</td>
<td>1969.22</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>59.59</td>
<td>1.80</td>
<td>1.25</td>
<td>1.74</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>0.00</td>
<td>0.25</td>
<td>43.42</td>
<td>1965.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>0.00</td>
<td>16.43</td>
<td>105.71</td>
<td>1968.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>4.00</td>
<td>17.12</td>
<td>106.16</td>
<td>1969.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>12.00</td>
<td>18.00</td>
<td>106.64</td>
<td>1970.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>9822.00</td>
<td>135.72</td>
<td>167.50</td>
<td>1975.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>And already, just from this description, we can make some simple but important inferences: for example that 75% of the bombings were carried out before or during the year 1970, despite the fact that the bombing campaign as a whole did not end until 1975 (which we can see from the <strong>max</strong> value of <code>year</code>)</p>
</section>
<section id="cross-tabulation-of-the-relationship-between-two-variables" class="level3">
<h3 class="anchored" data-anchor-id="cross-tabulation-of-the-relationship-between-two-variables">(6.2) Cross-Tabulation of the Relationship Between Two Variables</h3>
<p>If you googled “cross-tabulation in pandas” like the lab asks you to (which I hope you did in the days between the lab handout and this writeup!), you’ll find the Pandas function <code>crosstab()</code>.</p>
<p><code>crosstab()</code> works similarly to <code>describe()</code> except that, rather than computing summary statistics across the <strong>entire dataset</strong>, it computes a set of <strong>conditional summary statistics</strong>, so that we can use it e.g.&nbsp;to examine the distributions of a numeric variable (say, <code>year</code>) for different values of a <strong>categorical</strong> variable (say, <code>TGTCOUNTRY</code>). Here we use it with its default parameter settings to generate a table showing us the <strong>number of strikes</strong> within each cross-tabulated “bin”—that is, each <code>(year,country)</code> pair where <code>year</code> is some value in the <code>year</code> column and <code>country</code> is some value in the <code>TGTCOUNTRY</code> column:</p>
<div id="cell-92" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:58.238401Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:58.152516Z&quot;}" data-outputid="9097db4c-19c5-4d62-b94a-3b495651aa03" data-execution_count="41">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>pd.crosstab(strike_df[<span class="st">'year'</span>], strike_df[<span class="st">'TGTCOUNTRY'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">CAMBODIA</th>
<th data-quarto-table-cell-role="th">LAOS</th>
<th data-quarto-table-cell-role="th">NORTH VIETNAM</th>
<th data-quarto-table-cell-role="th">SOUTH VIETNAM</th>
<th data-quarto-table-cell-role="th">THAILAND</th>
<th data-quarto-table-cell-role="th">UNKNOWN</th>
<th data-quarto-table-cell-role="th">WESTPAC WATERS</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1965</td>
<td>0</td>
<td>1197</td>
<td>2596</td>
<td>9238</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1966</td>
<td>0</td>
<td>16825</td>
<td>24261</td>
<td>4918</td>
<td>11</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1967</td>
<td>18</td>
<td>29738</td>
<td>69420</td>
<td>1004</td>
<td>6</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1968</td>
<td>0</td>
<td>105046</td>
<td>108110</td>
<td>3763</td>
<td>81</td>
<td>19</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1969</td>
<td>23</td>
<td>167010</td>
<td>729</td>
<td>1353</td>
<td>41</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1970</td>
<td>6099</td>
<td>209273</td>
<td>1801</td>
<td>2684</td>
<td>7</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1971</td>
<td>1130</td>
<td>107675</td>
<td>3342</td>
<td>7932</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>1243</td>
<td>48531</td>
<td>34281</td>
<td>23303</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>4758</td>
<td>4866</td>
<td>1437</td>
<td>54</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1975</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>And again, especially with whatever domain knowledge we possess, we can detect patterns in this table that help us understand the underlying phenomena:</p>
<p>For example, we see that bombing runs in <strong>Cambodia</strong> were sporadic before 1970, but quickly jumped to a high of 6,099 in 1970, mirroring a turbulent event in Cambodian history that year</p>
<p><em>([very long story short,] Cambodia’s somewhat-popular leader <a href="https://en.wikipedia.org/wiki/Norodom_Sihanouk" target="_blank">Prince Sihanouk</a> was overthrown in a US-sponsored coup in 1970 and replaced by the less-popular army general <a href="https://en.wikipedia.org/wiki/Lon_Nol" target="_blank">Lon Nol</a>, leading the now-exiled-in-China Sihanouk to devote his energy towards supporting/accelerating communist [mostly, though not entirely, Khmer Rouge] resistance to the Lon Nol military dictatorship, which in turn led the US to begin bombing Khmer Rouge/other communist strongholds in support of the regime)</em></p>
<p>More relevant to our discussion of <strong>Laos</strong> in the beginning, though, we can also start to see how Laos became the most-bombed territory in history: unlike the other countries, wherein bombings had high “spikes” in some years but low-level “lulls” in other years, Laos was continually bombed over 100,000 times per year every year between 1968 and 1971 (inclusive).</p>
</section>
</section>
<section id="seaborn-time" class="level2">
<h2 class="anchored" data-anchor-id="seaborn-time">(7) Seaborn Time!</h2>
<p>As mentioned above (and just in case you’re running these cells without running the cells above first), we import <code>matplotlib</code> and <code>seaborn</code> using aliases as follows:</p>
<div id="cell-96" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T08:57:59.688643Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T08:57:59.666086Z&quot;}" data-execution_count="42">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="aggregation" class="level3">
<h3 class="anchored" data-anchor-id="aggregation">(7.1) Aggregation</h3>
<p>Now, since this data has a much larger number of rows than the cars-by-country dataset used in the W06 lab demonstration, using <code>sns.catplot()</code> will take a while to produce the same types of visualizations. So for our use case, we’re going to start off by working with <strong>aggregated</strong> data, to make the number of datapoints manageable and quickly visualizable using Seaborn.</p>
<p>As mentioned earlier (and as we saw in the cross-tabulation), we can start to get a good feel for “what’s going on” in the data by focusing on year-by-year statistics first, before “zooming in” on the particular months and/or days of the bombings. So, let’s perform that aggregation now: we’ll use Pandas’ <code>agg()</code> function to <strong>count</strong> the number of bombings per year in each country, while <strong>averaging</strong> the latitude and longitude and finding the <strong>maximum</strong> of the number of weapons delivered.</p>
<p>While averaging and maximizing might be a bit contrived in this example, in general this is where a lot of your thought should go when you are first starting on EDA! You should ask yourself which variables you want to <strong>group by</strong> (country, in our case) and which variables you want to <strong>aggregate</strong>, and for the latter set of variables which <strong>specific aggregations you want to apply</strong> that will best allow you to answer the types of EDA questions you are brainstorming.</p>
<p>For example, while at first I thought about computing the <strong>mode</strong> of the longitude and latitude per year, to try and find the most-bombed location in each country during each year, in reality the latitude and longitude values are too fine-grained, in that a single village being bombed might 100 times might show up as 100 different sets of coordinates, unless two planes happened to bomb the exact same point on earth down to the maximum possible level of precision in the numeric recording mechanism used by the US military, not a very likely prospect</p>
<p><em>(If that was confusing, it’s the same intuition around why, if we had 100 students each draw a unit circle and measure that circle’s circumference, all of these values would be approximately <span class="math inline">\(2\pi\)</span>, and yet it would be unlikely to find that any two students’ values were equal down to 50 or 100 decimal places)</em></p>
<p>So, let’s run the <code>agg()</code> function to compute these aggregate values! There are a ton of different ways to use this function, syntax-wise, but I find the following syntax to be the most flexible for my most common use-cases (if you are curious about other ways to use it, or you can’t get this to work as a “template” for the aggregations you are trying to perform, let me know/schedule an office hour!)</p>
<p><em>(Also, we are now going to drop the extraneous <code>id</code> functions that we kept along until now: I kept them in there because I want you to get comfortable with cases where you keep variables around just in case you end up needing them later on in your analysis, but since <code>agg()</code> requires an aggregation rule for each column in the dataset, I will just drop whatever values we’re not including in the aggregation at this point.)</em></p>
<div id="cell-99" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:39.198420Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:39.161912Z&quot;}" data-outputid="5b99b6d3-565e-49e8-8430-1e344a15c898" data-execution_count="43">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing the column names here for reference</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>strike_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>Index(['MFUNC_DESC', 'MISSIONID', 'TGTCOUNTRY', 'THOR_DATA_VIET_ID', 'MSNDATE',
       'SOURCEID', 'NUMWEAPONSDELIVERED', 'TGTTYPE', 'TGTLATDD_DDD_WGS84',
       'TGTLONDDD_DDD_WGS84', 'year'],
      dtype='object')</code></pre>
</div>
</div>
<p>Here, so that I have some actual column in the dataset that I can aggregate to get the <strong>count</strong> per group, I make a column called <code>num_bombings</code> filled with the value <code>1</code> for now, so that when we aggregate this column by <strong>summing it</strong>, the column will thereafter contain the <strong>count</strong> of the number of observations (bombings) per group</p>
<div id="cell-101" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:40.664861Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:40.636613Z&quot;}" data-execution_count="44">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>strike_df[<span class="st">'num_bombings'</span>] <span class="op">=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-102" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:40.890058Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:40.881679Z&quot;}" data-execution_count="45">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># And specifying columns to keep, that will be used as either *group* or</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co"># *aggregated* variables</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>cols_to_keep <span class="op">=</span> [</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTCOUNTRY'</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'year'</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTTYPE'</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NUMWEAPONSDELIVERED'</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTLATDD_DDD_WGS84'</span>,</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TGTLONDDD_DDD_WGS84'</span>,</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'num_bombings'</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-103" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:41.266488Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:41.122217Z&quot;}" data-execution_count="46">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># And run!</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>agg_df <span class="op">=</span> strike_df[cols_to_keep].groupby([<span class="st">'TGTCOUNTRY'</span>,<span class="st">'year'</span>,<span class="st">'TGTTYPE'</span>]).agg(</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    mean_weapons <span class="op">=</span> (<span class="st">'NUMWEAPONSDELIVERED'</span>, <span class="st">'mean'</span>),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    num_bombings <span class="op">=</span> (<span class="st">'num_bombings'</span>, <span class="st">'sum'</span>),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    mean_lat <span class="op">=</span> (<span class="st">'TGTLATDD_DDD_WGS84'</span>, <span class="st">'mean'</span>),</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>    mean_lon <span class="op">=</span> (<span class="st">'TGTLONDDD_DDD_WGS84'</span>, <span class="st">'mean'</span>),</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we can see from the output of <code>head()</code>, it looks like it <strong>has</strong> aggregated the data as we wanted, it’s just a bit messy since the aggregated data is grouped in a three-level hierarchy (country-&gt;year-&gt;target type):</p>
<div id="cell-105" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:42.336729Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:42.312362Z&quot;}" data-outputid="b5db0643-e00a-4bda-c4ff-07b90e8017b1" data-execution_count="47">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>agg_df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean_weapons</th>
<th data-quarto-table-cell-role="th">num_bombings</th>
<th data-quarto-table-cell-role="th">mean_lat</th>
<th data-quarto-table-cell-role="th">mean_lon</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">TGTTYPE</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">CAMBODIA</td>
<td rowspan="3" data-quarto-table-cell-role="th" data-valign="top">1967</td>
<td data-quarto-table-cell-role="th">AREA\DEPOT</td>
<td>3.333333</td>
<td>12</td>
<td>14.693574</td>
<td>106.988342</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ROAD</td>
<td>4.000000</td>
<td>2</td>
<td>14.675000</td>
<td>106.783333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">TRUCK PARK\STOP</td>
<td>12.750000</td>
<td>4</td>
<td>14.573833</td>
<td>106.990167</td>
</tr>
<tr class="even">
<td rowspan="2" data-quarto-table-cell-role="th" data-valign="top">1969</td>
<td data-quarto-table-cell-role="th">ANTI-AIRCRAFT</td>
<td>5.000000</td>
<td>11</td>
<td>14.298727</td>
<td>107.505909</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">UNKNOWN\UNIDENTIFIED</td>
<td>2.333333</td>
<td>12</td>
<td>14.593815</td>
<td>107.539481</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>If this type of hierarchical index is what you want for your use-case, then you’re done! In this case, though, we’d like to analyze various relationships among these variables which are unrelated to the specific country-&gt;year-&gt;target type hierarchy, so we’ll just use <code>reset_index()</code> (remembering to also include the <code>inplace = True</code> option!) to convert the hierarchical index columns into “regular” data columns:</p>
<div id="cell-107" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:48.105673Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:48.070885Z&quot;}" data-outputid="d25c5f63-5d07-43bb-e5a9-d3a1f07849bb" data-execution_count="48">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>agg_df.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>agg_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">TGTTYPE</th>
<th data-quarto-table-cell-role="th">mean_weapons</th>
<th data-quarto-table-cell-role="th">num_bombings</th>
<th data-quarto-table-cell-role="th">mean_lat</th>
<th data-quarto-table-cell-role="th">mean_lon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>CAMBODIA</td>
<td>1967</td>
<td>AREA\DEPOT</td>
<td>3.333333</td>
<td>12</td>
<td>14.693574</td>
<td>106.988342</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>CAMBODIA</td>
<td>1967</td>
<td>ROAD</td>
<td>4.000000</td>
<td>2</td>
<td>14.675000</td>
<td>106.783333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>CAMBODIA</td>
<td>1967</td>
<td>TRUCK PARK\STOP</td>
<td>12.750000</td>
<td>4</td>
<td>14.573833</td>
<td>106.990167</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>CAMBODIA</td>
<td>1969</td>
<td>ANTI-AIRCRAFT</td>
<td>5.000000</td>
<td>11</td>
<td>14.298727</td>
<td>107.505909</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>CAMBODIA</td>
<td>1969</td>
<td>UNKNOWN\UNIDENTIFIED</td>
<td>2.333333</td>
<td>12</td>
<td>14.593815</td>
<td>107.539481</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">229</td>
<td>UNKNOWN</td>
<td>1968</td>
<td>ROAD</td>
<td>0.800000</td>
<td>5</td>
<td>18.925000</td>
<td>105.595900</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">230</td>
<td>UNKNOWN</td>
<td>1968</td>
<td>SEGMENT\TRANS ROUTE</td>
<td>6.833333</td>
<td>6</td>
<td>18.401953</td>
<td>105.744138</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">231</td>
<td>UNKNOWN</td>
<td>1968</td>
<td>other</td>
<td>4.250000</td>
<td>8</td>
<td>16.690458</td>
<td>106.489083</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">232</td>
<td>UNKNOWN</td>
<td>1969</td>
<td>UNKNOWN\UNIDENTIFIED</td>
<td>0.000000</td>
<td>4</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">233</td>
<td>WESTPAC WATERS</td>
<td>1968</td>
<td>other</td>
<td>0.000000</td>
<td>6</td>
<td>17.566667</td>
<td>107.044389</td>
</tr>
</tbody>
</table>

<p>234 rows × 7 columns</p>
</div>
</div>
</div>
</div>
<p>As a final consideration before we create our Seaborn <code>catplot</code>s: if we had spent more time cleaning the <code>TGTTYPE</code> variable—for example, by collapsing the individual values down into a smaller set of categories like “people”, “vehicles”, “buildings”—that would provide us with another easy-to-analyze categorical variable. For the sake of getting through the visualizations without more code, though, I won’t be generating plots involving this variable, so I’m now going to aggregate our dataset one more time, to sum/average over the different target-type values for each (country, year) pair. But, if you decide you want to use this dataset for a project, you can stop here and clean <code>TGTTYPE</code> to carry out an EDA investigation in a different direction!</p>
<div id="cell-109" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:49.228648Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:49.194908Z&quot;}" data-execution_count="49">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>country_year_df <span class="op">=</span> strike_df.groupby([<span class="st">'TGTCOUNTRY'</span>,<span class="st">'year'</span>]).agg(</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>    mean_weapons <span class="op">=</span> (<span class="st">'NUMWEAPONSDELIVERED'</span>, <span class="st">'mean'</span>),</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>    num_bombings <span class="op">=</span> (<span class="st">'num_bombings'</span>, <span class="st">'sum'</span>),</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>    mean_lat <span class="op">=</span> (<span class="st">'TGTLATDD_DDD_WGS84'</span>, <span class="st">'mean'</span>),</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    mean_lon <span class="op">=</span> (<span class="st">'TGTLONDDD_DDD_WGS84'</span>, <span class="st">'mean'</span>),</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>).reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="categorical-plots-with-catplot" class="level3">
<h3 class="anchored" data-anchor-id="categorical-plots-with-catplot">(7.2) Categorical Plots with <code>catplot()</code></h3>
<p>Let’s generate our first <code>catplot()</code>! Here we’ll create a non-stacked bar plot, where the x-axis will represent years and the y-axis will represent number of bombings, while the bars themselves will be <strong>colored</strong> by country (the <code>hue</code> option in <code>catplot</code>:</p>
<div id="cell-112" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:54.612768Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:54.447333Z&quot;}" data-outputid="8199f586-66d9-436a-8617-5e929212802a" data-execution_count="50">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>sns.catplot(</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> country_year_df,</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    kind <span class="op">=</span> <span class="st">"bar"</span>,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">'year'</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">'num_bombings'</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">'TGTCOUNTRY'</span>,</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    orient <span class="op">=</span> <span class="st">'v'</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-47-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can already infer some things from this plot, but since there were so few bombings in Thailand and in the “Unknown” and “WESTPAC WATERS” categories, let’s exclude these to make the plot more readable (it may be tempting to drop them, and it would typically be ok in many cases, but data-science-wise it’s a bit sketchy in the sense that it would skew our results if we wanted to compute e.g.&nbsp;the <strong>proportion of all bombings</strong> in each country at some point in our analysis later on)</p>
<div id="cell-114" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:15:58.702544Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:15:58.401700Z&quot;}" data-outputid="a61fd7ef-9e49-4c18-b8fa-54a668ca4ca5" data-execution_count="51">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>countries_to_keep <span class="op">=</span> [</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'CAMBODIA'</span>,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'LAOS'</span>,</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NORTH VIETNAM'</span>,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SOUTH VIETNAM'</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>country_year_sub_df <span class="op">=</span> country_year_df.loc[</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>    country_year_df[<span class="st">'TGTCOUNTRY'</span>].isin(countries_to_keep),</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>sns.catplot(</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> country_year_sub_df,</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>    kind <span class="op">=</span> <span class="st">"bar"</span>,</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">'year'</span>,</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">'num_bombings'</span>,</span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">'TGTCOUNTRY'</span>,</span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>    orient <span class="op">=</span> <span class="st">'v'</span></span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-48-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>So for me, at least, the plot in this form really already drives home the point from the beginning of the writeup: that “The Vietnam War” really could be called “The Vietnam War Plus The Continuous Onslaught Of Modern Weaponry Rained Down Upon Laos, A Similarly Poor And Agrarian Country With A Fraction Of The Population Of Vietnam”.</p>
</section>
<section id="plotting-non-aggregated-data" class="level3">
<h3 class="anchored" data-anchor-id="plotting-non-aggregated-data">(7.3) Plotting Non-Aggregated Data</h3>
<p>Now that we’ve seen how to make a basic <code>catplot()</code> using aggregated data, we can move back to the <strong>non</strong>-aggregated (individual-bombing level) data to see how <code>catplot()</code> can <strong>automatically</strong> aggregate data for us, in whatever way enables it to make the plot we ask for. This is a super powerful function, in that sense, it just runs much more slowly (so I wanted to show some quick-to-generate examples first!)</p>
<p>Looking again at the columns in <code>strike_df</code> here, as a reminder:</p>
<div id="cell-118" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:12:51.736479Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:12:51.722323Z&quot;}" data-execution_count="52">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>strike_df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<pre><code>Index(['MFUNC_DESC', 'MISSIONID', 'TGTCOUNTRY', 'THOR_DATA_VIET_ID', 'MSNDATE',
       'SOURCEID', 'NUMWEAPONSDELIVERED', 'TGTTYPE', 'TGTLATDD_DDD_WGS84',
       'TGTLONDDD_DDD_WGS84', 'year', 'num_bombings'],
      dtype='object')</code></pre>
</div>
</div>
<p>We see that so far we’ve neglected the <code>NUMWEAPONSDELIVERED</code> variable. Let’s use a <strong>violin plot</strong> this time to see what the data within this variable looks like:</p>
<div id="cell-120" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2023-09-30T09:13:50.309981Z&quot;,&quot;start_time&quot;:&quot;2023-09-30T09:13:48.231290Z&quot;}" data-execution_count="53">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>strike_sub_df <span class="op">=</span> strike_df.loc[strike_df[<span class="st">'TGTCOUNTRY'</span>].isin(countries_to_keep),].copy()</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>sns.catplot(</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>strike_sub_df,</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    kind<span class="op">=</span><span class="st">'violin'</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">'NUMWEAPONSDELIVERED'</span>,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">'TGTCOUNTRY'</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">'TGTCOUNTRY'</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-50-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Although we now see that violin plots are probably <strong>not</strong> the best way to visualize this variable. In general violin plots are intended to plot the “curvature” of a distribution over some range of values, but in this case the distribution of our data is almost entirely concentrated at 0, with a few very extreme outlier values. We can still make some inferences, however: like how Laos was not only the <strong>most bombed</strong> country, but also the country which experienced the largest single bombing of the entire campaign—the extreme outlier corresponding to a bombing run where over 8000 were delivered to the target.</p>
<p>Finally, while we unfortunately don’t have two full-on continuous numeric variables to plot in the form of (e.g.) a scatterplot, we can use the year of each mission as a type of pseudo-continous numeric variable (the full date would be even better, if we wanted to spend more time cleaning the date variable so we could visualize the day-by-day statistics), plotted against the <code>NUMWEAPONSDELIVERED</code> value for that mission (similar to the bar graph from above, but this time generated <strong>automatically</strong> by Seaborn from the raw, non-aggregated data):</p>
<div id="cell-123" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here, (1) Again we use strike_sub_df to filter out the countries outside of our 4 main countries</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and thus make the plot slightly more readable, and (2) I'm using Pandas' sample() function to</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="co"># make the number of points manageable for Seaborn to plot (since otherwise it takes over a minute,</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># which is mostly spent drawing nearly 1 million points that are almost entirely down near 0)</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>strike_sub_sample_df <span class="op">=</span> strike_sub_df.sample(<span class="dv">10000</span>)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>sns.lmplot(</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>strike_sub_sample_df, </span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"year"</span>,</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"NUMWEAPONSDELIVERED"</span>,</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>    col<span class="op">=</span><span class="st">"TGTCOUNTRY"</span>,</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>    hue<span class="op">=</span><span class="st">"TGTCOUNTRY"</span>)</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/Users/jpj/.pyenv/versions/3.11.5/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-51-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>And from these four plots we see what we could already probably see in the <strong>tabulations</strong> from earlier: that Cambodia is the only country which saw a clear year-to-year <strong>increase</strong> in bombings experienced, from the 1970 coup onwards. As another potential “branching path” in our EDA journey, we could feasibly dive far more deeply into this phenomenon in the Cambodia data specifically: visualizing these bombing-rate increases at a more fine-grained daily level, for example, and seeing whether/how they relate to political and military developments in Sihanouk’s/China’s backing of the Khmer Rouge.</p>
<p>And, last but certainly not least, a <strong>correlogram</strong> of our <strong>aggregated</strong> variables, generated using the same code as used in the W06 lab demo (we first display the full <code>country_year_sub_df</code>, so we can glance back and forth between the correlations encoded as colors in the correlogram and the values themselves)</p>
<div id="cell-126" class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>country_year_sub_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="55">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TGTCOUNTRY</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">mean_weapons</th>
<th data-quarto-table-cell-role="th">num_bombings</th>
<th data-quarto-table-cell-role="th">mean_lat</th>
<th data-quarto-table-cell-role="th">mean_lon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>CAMBODIA</td>
<td>1967</td>
<td>5.500000</td>
<td>18</td>
<td>14.664901</td>
<td>106.965969</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>CAMBODIA</td>
<td>1969</td>
<td>3.608696</td>
<td>23</td>
<td>14.452686</td>
<td>107.523425</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>CAMBODIA</td>
<td>1970</td>
<td>19.907526</td>
<td>6099</td>
<td>12.656550</td>
<td>106.588893</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>CAMBODIA</td>
<td>1971</td>
<td>84.664602</td>
<td>1130</td>
<td>13.221369</td>
<td>106.461660</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>CAMBODIA</td>
<td>1972</td>
<td>80.004827</td>
<td>1243</td>
<td>12.587244</td>
<td>106.407726</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>CAMBODIA</td>
<td>1973</td>
<td>106.332072</td>
<td>4758</td>
<td>11.898209</td>
<td>105.176818</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>LAOS</td>
<td>1965</td>
<td>10.939850</td>
<td>1197</td>
<td>17.552708</td>
<td>105.521857</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>LAOS</td>
<td>1966</td>
<td>11.938068</td>
<td>16825</td>
<td>16.618527</td>
<td>106.264797</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>LAOS</td>
<td>1967</td>
<td>12.266561</td>
<td>29738</td>
<td>16.364346</td>
<td>106.365654</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>LAOS</td>
<td>1968</td>
<td>9.391200</td>
<td>105046</td>
<td>17.052071</td>
<td>105.898343</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>LAOS</td>
<td>1969</td>
<td>10.355326</td>
<td>167010</td>
<td>17.470780</td>
<td>105.498338</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>LAOS</td>
<td>1970</td>
<td>11.221041</td>
<td>209273</td>
<td>17.145868</td>
<td>105.686660</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>LAOS</td>
<td>1971</td>
<td>13.407160</td>
<td>107675</td>
<td>17.140651</td>
<td>105.549005</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>LAOS</td>
<td>1972</td>
<td>18.685891</td>
<td>48531</td>
<td>17.093275</td>
<td>105.228933</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>LAOS</td>
<td>1973</td>
<td>46.943280</td>
<td>4866</td>
<td>17.607340</td>
<td>104.471988</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>NORTH VIETNAM</td>
<td>1965</td>
<td>12.527735</td>
<td>2596</td>
<td>20.248847</td>
<td>105.176626</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>NORTH VIETNAM</td>
<td>1966</td>
<td>9.555418</td>
<td>24261</td>
<td>18.333420</td>
<td>106.140361</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>NORTH VIETNAM</td>
<td>1967</td>
<td>9.060746</td>
<td>69420</td>
<td>18.516883</td>
<td>106.320436</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>NORTH VIETNAM</td>
<td>1968</td>
<td>7.279752</td>
<td>108110</td>
<td>17.895921</td>
<td>106.223039</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>NORTH VIETNAM</td>
<td>1969</td>
<td>2.847737</td>
<td>729</td>
<td>17.957101</td>
<td>106.128279</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>NORTH VIETNAM</td>
<td>1970</td>
<td>7.349806</td>
<td>1801</td>
<td>17.063296</td>
<td>105.956814</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>NORTH VIETNAM</td>
<td>1971</td>
<td>12.736385</td>
<td>3342</td>
<td>17.170001</td>
<td>106.070248</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>NORTH VIETNAM</td>
<td>1972</td>
<td>14.750387</td>
<td>34281</td>
<td>18.364637</td>
<td>106.144553</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>NORTH VIETNAM</td>
<td>1973</td>
<td>28.956159</td>
<td>1437</td>
<td>18.439947</td>
<td>105.850921</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>SOUTH VIETNAM</td>
<td>1965</td>
<td>13.495670</td>
<td>9238</td>
<td>13.340375</td>
<td>107.601053</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>SOUTH VIETNAM</td>
<td>1966</td>
<td>13.735665</td>
<td>4918</td>
<td>13.053547</td>
<td>107.553177</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>SOUTH VIETNAM</td>
<td>1967</td>
<td>9.340637</td>
<td>1004</td>
<td>15.226087</td>
<td>107.357685</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>SOUTH VIETNAM</td>
<td>1968</td>
<td>11.776774</td>
<td>3763</td>
<td>15.712929</td>
<td>107.287747</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>SOUTH VIETNAM</td>
<td>1969</td>
<td>17.725795</td>
<td>1353</td>
<td>14.273498</td>
<td>107.630294</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>SOUTH VIETNAM</td>
<td>1970</td>
<td>8.029434</td>
<td>2684</td>
<td>14.339186</td>
<td>107.127581</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>SOUTH VIETNAM</td>
<td>1971</td>
<td>7.367625</td>
<td>7932</td>
<td>16.382974</td>
<td>106.494151</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">31</td>
<td>SOUTH VIETNAM</td>
<td>1972</td>
<td>7.496674</td>
<td>23303</td>
<td>14.872121</td>
<td>106.908634</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">32</td>
<td>SOUTH VIETNAM</td>
<td>1973</td>
<td>95.425926</td>
<td>54</td>
<td>13.715959</td>
<td>107.502381</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">33</td>
<td>SOUTH VIETNAM</td>
<td>1975</td>
<td>1.000000</td>
<td>4</td>
<td>11.007222</td>
<td>106.834444</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="cell-127" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>corr_vars <span class="op">=</span> [<span class="st">'mean_weapons'</span>, <span class="st">'num_bombings'</span>, <span class="st">'mean_lat'</span>, <span class="st">'mean_lon'</span>]</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> country_year_sub_df[corr_vars].corr()  <span class="co">#Compute the correlation matrix</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a mask for the upper triangle</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.triu(np.ones_like(corr, dtype<span class="op">=</span><span class="bu">bool</span>)) </span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">9</span>)) <span class="co">#initialize figure</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> sns.diverging_palette(<span class="dv">230</span>, <span class="dv">20</span>, as_cmap<span class="op">=</span><span class="va">True</span>) <span class="co">#custom diverging colormap</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># # Draw the heatmap with the mask and correct aspect ratio</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr, mask<span class="op">=</span>mask, cmap<span class="op">=</span>cmap, vmax<span class="op">=</span><span class="fl">.3</span>, center<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>                square<span class="op">=</span><span class="va">True</span>, linewidths<span class="op">=</span><span class="fl">.5</span>, cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.5</span>})</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="THOR_EDA_with_Seaborn_files/figure-html/cell-53-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>My old link to the dataset, from <code>data.mil</code>, does not seem to work anymore, and I can’t locate this dataset on the Department of Defense’s official website anymore, so if someone knows what happened there let me know :D<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>